// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.ActivePeriodList}
 */
public final class ActivePeriodList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.ActivePeriodList)
    ActivePeriodListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ActivePeriodList.newBuilder() to construct.
  private ActivePeriodList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ActivePeriodList() {
    type_ = 0;
    activePeriodList_ = "";
    nonActiveperiodList_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ActivePeriodList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_ActivePeriodList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_ActivePeriodList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.class, com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.ActivePeriodList.scheduleType}
   */
  public enum scheduleType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EVERYDAY = 0;</code>
     */
    EVERYDAY(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EVERYDAY = 0;</code>
     */
    public static final int EVERYDAY_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static scheduleType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static scheduleType forNumber(int value) {
      switch (value) {
        case 0: return EVERYDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<scheduleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        scheduleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<scheduleType>() {
            public scheduleType findValueByNumber(int number) {
              return scheduleType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.getDescriptor().getEnumTypes().get(0);
    }

    private static final scheduleType[] VALUES = values();

    public static scheduleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private scheduleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.ActivePeriodList.scheduleType)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType getType() {
    com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType result = com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType.forNumber(type_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType.UNRECOGNIZED : result;
  }

  public static final int ACTIVEPERIODLIST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object activePeriodList_ = "";
  /**
   * <code>string activePeriodList = 2;</code>
   * @return The activePeriodList.
   */
  @java.lang.Override
  public java.lang.String getActivePeriodList() {
    java.lang.Object ref = activePeriodList_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      activePeriodList_ = s;
      return s;
    }
  }
  /**
   * <code>string activePeriodList = 2;</code>
   * @return The bytes for activePeriodList.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActivePeriodListBytes() {
    java.lang.Object ref = activePeriodList_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      activePeriodList_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NON_ACTIVEPERIODLIST_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nonActiveperiodList_ = "";
  /**
   * <code>string non_ActiveperiodList = 3;</code>
   * @return The nonActiveperiodList.
   */
  @java.lang.Override
  public java.lang.String getNonActiveperiodList() {
    java.lang.Object ref = nonActiveperiodList_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nonActiveperiodList_ = s;
      return s;
    }
  }
  /**
   * <code>string non_ActiveperiodList = 3;</code>
   * @return The bytes for nonActiveperiodList.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNonActiveperiodListBytes() {
    java.lang.Object ref = nonActiveperiodList_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonActiveperiodList_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLAG_FIELD_NUMBER = 4;
  private boolean flag_ = false;
  /**
   * <code>bool flag = 4;</code>
   * @return The flag.
   */
  @java.lang.Override
  public boolean getFlag() {
    return flag_;
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType.EVERYDAY.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(activePeriodList_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, activePeriodList_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonActiveperiodList_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nonActiveperiodList_);
    }
    if (flag_ != false) {
      output.writeBool(4, flag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, status_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType.EVERYDAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(activePeriodList_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, activePeriodList_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonActiveperiodList_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nonActiveperiodList_);
    }
    if (flag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, flag_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, status_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.ActivePeriodList)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.ActivePeriodList other = (com.resideo.utils.stat.cattgrpccommands.ActivePeriodList) obj;

    if (type_ != other.type_) return false;
    if (!getActivePeriodList()
        .equals(other.getActivePeriodList())) return false;
    if (!getNonActiveperiodList()
        .equals(other.getNonActiveperiodList())) return false;
    if (getFlag()
        != other.getFlag()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + ACTIVEPERIODLIST_FIELD_NUMBER;
    hash = (53 * hash) + getActivePeriodList().hashCode();
    hash = (37 * hash) + NON_ACTIVEPERIODLIST_FIELD_NUMBER;
    hash = (53 * hash) + getNonActiveperiodList().hashCode();
    hash = (37 * hash) + FLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFlag());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.ActivePeriodList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.ActivePeriodList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.ActivePeriodList)
      com.resideo.utils.stat.cattgrpccommands.ActivePeriodListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_ActivePeriodList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_ActivePeriodList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.class, com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      activePeriodList_ = "";
      nonActiveperiodList_ = "";
      flag_ = false;
      status_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_ActivePeriodList_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.ActivePeriodList getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.ActivePeriodList build() {
      com.resideo.utils.stat.cattgrpccommands.ActivePeriodList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.ActivePeriodList buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.ActivePeriodList result = new com.resideo.utils.stat.cattgrpccommands.ActivePeriodList(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.ActivePeriodList result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.activePeriodList_ = activePeriodList_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nonActiveperiodList_ = nonActiveperiodList_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.flag_ = flag_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.status_ = status_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.ActivePeriodList) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.ActivePeriodList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.ActivePeriodList other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (!other.getActivePeriodList().isEmpty()) {
        activePeriodList_ = other.activePeriodList_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getNonActiveperiodList().isEmpty()) {
        nonActiveperiodList_ = other.nonActiveperiodList_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getFlag() != false) {
        setFlag(other.getFlag());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              activePeriodList_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              nonActiveperiodList_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              flag_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType getType() {
      com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType result = com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType.forNumber(type_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.resideo.utils.stat.cattgrpccommands.ActivePeriodList.scheduleType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.ActivePeriodList.scheduleType Type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object activePeriodList_ = "";
    /**
     * <code>string activePeriodList = 2;</code>
     * @return The activePeriodList.
     */
    public java.lang.String getActivePeriodList() {
      java.lang.Object ref = activePeriodList_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        activePeriodList_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string activePeriodList = 2;</code>
     * @return The bytes for activePeriodList.
     */
    public com.google.protobuf.ByteString
        getActivePeriodListBytes() {
      java.lang.Object ref = activePeriodList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        activePeriodList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string activePeriodList = 2;</code>
     * @param value The activePeriodList to set.
     * @return This builder for chaining.
     */
    public Builder setActivePeriodList(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      activePeriodList_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string activePeriodList = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearActivePeriodList() {
      activePeriodList_ = getDefaultInstance().getActivePeriodList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string activePeriodList = 2;</code>
     * @param value The bytes for activePeriodList to set.
     * @return This builder for chaining.
     */
    public Builder setActivePeriodListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      activePeriodList_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object nonActiveperiodList_ = "";
    /**
     * <code>string non_ActiveperiodList = 3;</code>
     * @return The nonActiveperiodList.
     */
    public java.lang.String getNonActiveperiodList() {
      java.lang.Object ref = nonActiveperiodList_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nonActiveperiodList_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string non_ActiveperiodList = 3;</code>
     * @return The bytes for nonActiveperiodList.
     */
    public com.google.protobuf.ByteString
        getNonActiveperiodListBytes() {
      java.lang.Object ref = nonActiveperiodList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonActiveperiodList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string non_ActiveperiodList = 3;</code>
     * @param value The nonActiveperiodList to set.
     * @return This builder for chaining.
     */
    public Builder setNonActiveperiodList(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nonActiveperiodList_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string non_ActiveperiodList = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonActiveperiodList() {
      nonActiveperiodList_ = getDefaultInstance().getNonActiveperiodList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string non_ActiveperiodList = 3;</code>
     * @param value The bytes for nonActiveperiodList to set.
     * @return This builder for chaining.
     */
    public Builder setNonActiveperiodListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nonActiveperiodList_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean flag_ ;
    /**
     * <code>bool flag = 4;</code>
     * @return The flag.
     */
    @java.lang.Override
    public boolean getFlag() {
      return flag_;
    }
    /**
     * <code>bool flag = 4;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(boolean value) {

      flag_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool flag = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {
      bitField0_ = (bitField0_ & ~0x00000008);
      flag_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 5;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 5;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.ActivePeriodList)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.ActivePeriodList)
  private static final com.resideo.utils.stat.cattgrpccommands.ActivePeriodList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.ActivePeriodList();
  }

  public static com.resideo.utils.stat.cattgrpccommands.ActivePeriodList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActivePeriodList>
      PARSER = new com.google.protobuf.AbstractParser<ActivePeriodList>() {
    @java.lang.Override
    public ActivePeriodList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActivePeriodList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActivePeriodList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.ActivePeriodList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

