// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.CreateSchedule}
 */
public final class CreateSchedule extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.CreateSchedule)
    CreateScheduleOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateSchedule.newBuilder() to construct.
  private CreateSchedule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateSchedule() {
    scheduleType_ = 0;
    dayList_ = "";
    update_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateSchedule();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_CreateSchedule_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_CreateSchedule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.CreateSchedule.class, com.resideo.utils.stat.cattgrpccommands.CreateSchedule.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.CreateSchedule.createType}
   */
  public enum createType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EVERYDAY = 0;</code>
     */
    EVERYDAY(0),
    /**
     * <code>WEEKDAY_WEEKEND = 1;</code>
     */
    WEEKDAY_WEEKEND(1),
    /**
     * <code>LET_ME_CHOOSE = 2;</code>
     */
    LET_ME_CHOOSE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EVERYDAY = 0;</code>
     */
    public static final int EVERYDAY_VALUE = 0;
    /**
     * <code>WEEKDAY_WEEKEND = 1;</code>
     */
    public static final int WEEKDAY_WEEKEND_VALUE = 1;
    /**
     * <code>LET_ME_CHOOSE = 2;</code>
     */
    public static final int LET_ME_CHOOSE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static createType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static createType forNumber(int value) {
      switch (value) {
        case 0: return EVERYDAY;
        case 1: return WEEKDAY_WEEKEND;
        case 2: return LET_ME_CHOOSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<createType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        createType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<createType>() {
            public createType findValueByNumber(int number) {
              return createType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CreateSchedule.getDescriptor().getEnumTypes().get(0);
    }

    private static final createType[] VALUES = values();

    public static createType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private createType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.CreateSchedule.createType)
  }

  /**
   * Protobuf enum {@code GrpcServices.CreateSchedule.enable_Disable}
   */
  public enum enable_Disable
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ENABLE = 0;</code>
     */
    ENABLE(0),
    /**
     * <code>DISABLE = 1;</code>
     */
    DISABLE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ENABLE = 0;</code>
     */
    public static final int ENABLE_VALUE = 0;
    /**
     * <code>DISABLE = 1;</code>
     */
    public static final int DISABLE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static enable_Disable valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static enable_Disable forNumber(int value) {
      switch (value) {
        case 0: return ENABLE;
        case 1: return DISABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<enable_Disable>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        enable_Disable> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<enable_Disable>() {
            public enable_Disable findValueByNumber(int number) {
              return enable_Disable.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CreateSchedule.getDescriptor().getEnumTypes().get(1);
    }

    private static final enable_Disable[] VALUES = values();

    public static enable_Disable valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private enable_Disable(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.CreateSchedule.enable_Disable)
  }

  public static final int SCHEDULETYPE_FIELD_NUMBER = 1;
  private int scheduleType_ = 0;
  /**
   * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
   * @return The enum numeric value on the wire for scheduleType.
   */
  @java.lang.Override public int getScheduleTypeValue() {
    return scheduleType_;
  }
  /**
   * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
   * @return The scheduleType.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType getScheduleType() {
    com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType result = com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType.forNumber(scheduleType_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType.UNRECOGNIZED : result;
  }

  public static final int DAYLIST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dayList_ = "";
  /**
   * <code>string dayList = 2;</code>
   * @return The dayList.
   */
  @java.lang.Override
  public java.lang.String getDayList() {
    java.lang.Object ref = dayList_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dayList_ = s;
      return s;
    }
  }
  /**
   * <code>string dayList = 2;</code>
   * @return The bytes for dayList.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDayListBytes() {
    java.lang.Object ref = dayList_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dayList_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATE_FIELD_NUMBER = 3;
  private int update_ = 0;
  /**
   * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
   * @return The enum numeric value on the wire for update.
   */
  @java.lang.Override public int getUpdateValue() {
    return update_;
  }
  /**
   * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
   * @return The update.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable getUpdate() {
    com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable result = com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable.forNumber(update_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scheduleType_ != com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType.EVERYDAY.getNumber()) {
      output.writeEnum(1, scheduleType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dayList_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dayList_);
    }
    if (update_ != com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable.ENABLE.getNumber()) {
      output.writeEnum(3, update_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scheduleType_ != com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType.EVERYDAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, scheduleType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dayList_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dayList_);
    }
    if (update_ != com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable.ENABLE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, update_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.CreateSchedule)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.CreateSchedule other = (com.resideo.utils.stat.cattgrpccommands.CreateSchedule) obj;

    if (scheduleType_ != other.scheduleType_) return false;
    if (!getDayList()
        .equals(other.getDayList())) return false;
    if (update_ != other.update_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEDULETYPE_FIELD_NUMBER;
    hash = (53 * hash) + scheduleType_;
    hash = (37 * hash) + DAYLIST_FIELD_NUMBER;
    hash = (53 * hash) + getDayList().hashCode();
    hash = (37 * hash) + UPDATE_FIELD_NUMBER;
    hash = (53 * hash) + update_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.CreateSchedule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.CreateSchedule}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.CreateSchedule)
      com.resideo.utils.stat.cattgrpccommands.CreateScheduleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_CreateSchedule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_CreateSchedule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.CreateSchedule.class, com.resideo.utils.stat.cattgrpccommands.CreateSchedule.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.CreateSchedule.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      scheduleType_ = 0;
      dayList_ = "";
      update_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_CreateSchedule_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.CreateSchedule getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.CreateSchedule.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.CreateSchedule build() {
      com.resideo.utils.stat.cattgrpccommands.CreateSchedule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.CreateSchedule buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.CreateSchedule result = new com.resideo.utils.stat.cattgrpccommands.CreateSchedule(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.CreateSchedule result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.scheduleType_ = scheduleType_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.dayList_ = dayList_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.update_ = update_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.CreateSchedule) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.CreateSchedule)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.CreateSchedule other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.CreateSchedule.getDefaultInstance()) return this;
      if (other.scheduleType_ != 0) {
        setScheduleTypeValue(other.getScheduleTypeValue());
      }
      if (!other.getDayList().isEmpty()) {
        dayList_ = other.dayList_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.update_ != 0) {
        setUpdateValue(other.getUpdateValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              scheduleType_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              dayList_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              update_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int scheduleType_ = 0;
    /**
     * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
     * @return The enum numeric value on the wire for scheduleType.
     */
    @java.lang.Override public int getScheduleTypeValue() {
      return scheduleType_;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
     * @param value The enum numeric value on the wire for scheduleType to set.
     * @return This builder for chaining.
     */
    public Builder setScheduleTypeValue(int value) {
      scheduleType_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
     * @return The scheduleType.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType getScheduleType() {
      com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType result = com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType.forNumber(scheduleType_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
     * @param value The scheduleType to set.
     * @return This builder for chaining.
     */
    public Builder setScheduleType(com.resideo.utils.stat.cattgrpccommands.CreateSchedule.createType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      scheduleType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.createType scheduleType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScheduleType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      scheduleType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dayList_ = "";
    /**
     * <code>string dayList = 2;</code>
     * @return The dayList.
     */
    public java.lang.String getDayList() {
      java.lang.Object ref = dayList_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dayList_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dayList = 2;</code>
     * @return The bytes for dayList.
     */
    public com.google.protobuf.ByteString
        getDayListBytes() {
      java.lang.Object ref = dayList_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dayList_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dayList = 2;</code>
     * @param value The dayList to set.
     * @return This builder for chaining.
     */
    public Builder setDayList(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dayList_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string dayList = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDayList() {
      dayList_ = getDefaultInstance().getDayList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string dayList = 2;</code>
     * @param value The bytes for dayList to set.
     * @return This builder for chaining.
     */
    public Builder setDayListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dayList_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int update_ = 0;
    /**
     * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
     * @return The enum numeric value on the wire for update.
     */
    @java.lang.Override public int getUpdateValue() {
      return update_;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
     * @param value The enum numeric value on the wire for update to set.
     * @return This builder for chaining.
     */
    public Builder setUpdateValue(int value) {
      update_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
     * @return The update.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable getUpdate() {
      com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable result = com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable.forNumber(update_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
     * @param value The update to set.
     * @return This builder for chaining.
     */
    public Builder setUpdate(com.resideo.utils.stat.cattgrpccommands.CreateSchedule.enable_Disable value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      update_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.CreateSchedule.enable_Disable update = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      update_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.CreateSchedule)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.CreateSchedule)
  private static final com.resideo.utils.stat.cattgrpccommands.CreateSchedule DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.CreateSchedule();
  }

  public static com.resideo.utils.stat.cattgrpccommands.CreateSchedule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateSchedule>
      PARSER = new com.google.protobuf.AbstractParser<CreateSchedule>() {
    @java.lang.Override
    public CreateSchedule parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateSchedule> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateSchedule> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.CreateSchedule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

