// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.DeviceCloudEnvironmentTypeMsg}
 */
public final class DeviceCloudEnvironmentTypeMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.DeviceCloudEnvironmentTypeMsg)
    DeviceCloudEnvironmentTypeMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceCloudEnvironmentTypeMsg.newBuilder() to construct.
  private DeviceCloudEnvironmentTypeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceCloudEnvironmentTypeMsg() {
    environment_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceCloudEnvironmentTypeMsg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_DeviceCloudEnvironmentTypeMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_DeviceCloudEnvironmentTypeMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.class, com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment}
   */
  public enum Environment
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>QA = 0;</code>
     */
    QA(0),
    /**
     * <code>STAGE = 1;</code>
     */
    STAGE(1),
    /**
     * <code>PROD = 2;</code>
     */
    PROD(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>QA = 0;</code>
     */
    public static final int QA_VALUE = 0;
    /**
     * <code>STAGE = 1;</code>
     */
    public static final int STAGE_VALUE = 1;
    /**
     * <code>PROD = 2;</code>
     */
    public static final int PROD_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Environment valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Environment forNumber(int value) {
      switch (value) {
        case 0: return QA;
        case 1: return STAGE;
        case 2: return PROD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Environment>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Environment> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Environment>() {
            public Environment findValueByNumber(int number) {
              return Environment.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final Environment[] VALUES = values();

    public static Environment valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Environment(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment)
  }

  public static final int ENVIRONMENT_FIELD_NUMBER = 1;
  private int environment_ = 0;
  /**
   * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
   * @return The enum numeric value on the wire for environment.
   */
  @java.lang.Override public int getEnvironmentValue() {
    return environment_;
  }
  /**
   * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
   * @return The environment.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment getEnvironment() {
    com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment result = com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment.forNumber(environment_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (environment_ != com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment.QA.getNumber()) {
      output.writeEnum(1, environment_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (environment_ != com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment.QA.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, environment_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg other = (com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg) obj;

    if (environment_ != other.environment_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENVIRONMENT_FIELD_NUMBER;
    hash = (53 * hash) + environment_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.DeviceCloudEnvironmentTypeMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.DeviceCloudEnvironmentTypeMsg)
      com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_DeviceCloudEnvironmentTypeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_DeviceCloudEnvironmentTypeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.class, com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      environment_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_DeviceCloudEnvironmentTypeMsg_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg build() {
      com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg result = new com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.environment_ = environment_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.getDefaultInstance()) return this;
      if (other.environment_ != 0) {
        setEnvironmentValue(other.getEnvironmentValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              environment_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int environment_ = 0;
    /**
     * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
     * @return The enum numeric value on the wire for environment.
     */
    @java.lang.Override public int getEnvironmentValue() {
      return environment_;
    }
    /**
     * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
     * @param value The enum numeric value on the wire for environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironmentValue(int value) {
      environment_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
     * @return The environment.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment getEnvironment() {
      com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment result = com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment.forNumber(environment_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
     * @param value The environment to set.
     * @return This builder for chaining.
     */
    public Builder setEnvironment(com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg.Environment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      environment_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.DeviceCloudEnvironmentTypeMsg.Environment environment = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnvironment() {
      bitField0_ = (bitField0_ & ~0x00000001);
      environment_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.DeviceCloudEnvironmentTypeMsg)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.DeviceCloudEnvironmentTypeMsg)
  private static final com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg();
  }

  public static com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceCloudEnvironmentTypeMsg>
      PARSER = new com.google.protobuf.AbstractParser<DeviceCloudEnvironmentTypeMsg>() {
    @java.lang.Override
    public DeviceCloudEnvironmentTypeMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeviceCloudEnvironmentTypeMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceCloudEnvironmentTypeMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.DeviceCloudEnvironmentTypeMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

