// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface extraOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.extra)
    com.google.protobuf.MessageOrBuilder {
}
