// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.FujiDisplayTextMsg}
 */
public final class FujiDisplayTextMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.FujiDisplayTextMsg)
    FujiDisplayTextMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FujiDisplayTextMsg.newBuilder() to construct.
  private FujiDisplayTextMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FujiDisplayTextMsg() {
    displayArea_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FujiDisplayTextMsg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_FujiDisplayTextMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_FujiDisplayTextMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.class, com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.FujiDisplayTextMsg.FujiDisplayArea}
   */
  public enum FujiDisplayArea
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>VerifiedArea_Setpoint = 0;</code>
     */
    VerifiedArea_Setpoint(0),
    /**
     * <code>VerifiedArea_IndoorTemp = 1;</code>
     */
    VerifiedArea_IndoorTemp(1),
    /**
     * <code>VerifiedArea_OutdoorTemp = 2;</code>
     */
    VerifiedArea_OutdoorTemp(2),
    /**
     * <code>VerifiedArea_Humidity = 3;</code>
     */
    VerifiedArea_Humidity(3),
    /**
     * <code>VerifiedArea_Time = 4;</code>
     */
    VerifiedArea_Time(4),
    /**
     * <code>VerifiedArea_Date_Year = 5;</code>
     */
    VerifiedArea_Date_Year(5),
    /**
     * <code>VerifiedArea_Date_Day = 6;</code>
     */
    VerifiedArea_Date_Day(6),
    /**
     * <code>VerifiedArea_InstallerTest_Stage = 7;</code>
     */
    VerifiedArea_InstallerTest_Stage(7),
    /**
     * <code>VerifiedArea_Pin = 8;</code>
     */
    VerifiedArea_Pin(8),
    /**
     * <code>VerifiedArea_IsuId = 9;</code>
     */
    VerifiedArea_IsuId(9),
    /**
     * <code>VerifiedArea_IsuValue = 10;</code>
     */
    VerifiedArea_IsuValue(10),
    /**
     * <code>VerifiedArea_Multitext = 11;</code>
     */
    VerifiedArea_Multitext(11),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>VerifiedArea_Setpoint = 0;</code>
     */
    public static final int VerifiedArea_Setpoint_VALUE = 0;
    /**
     * <code>VerifiedArea_IndoorTemp = 1;</code>
     */
    public static final int VerifiedArea_IndoorTemp_VALUE = 1;
    /**
     * <code>VerifiedArea_OutdoorTemp = 2;</code>
     */
    public static final int VerifiedArea_OutdoorTemp_VALUE = 2;
    /**
     * <code>VerifiedArea_Humidity = 3;</code>
     */
    public static final int VerifiedArea_Humidity_VALUE = 3;
    /**
     * <code>VerifiedArea_Time = 4;</code>
     */
    public static final int VerifiedArea_Time_VALUE = 4;
    /**
     * <code>VerifiedArea_Date_Year = 5;</code>
     */
    public static final int VerifiedArea_Date_Year_VALUE = 5;
    /**
     * <code>VerifiedArea_Date_Day = 6;</code>
     */
    public static final int VerifiedArea_Date_Day_VALUE = 6;
    /**
     * <code>VerifiedArea_InstallerTest_Stage = 7;</code>
     */
    public static final int VerifiedArea_InstallerTest_Stage_VALUE = 7;
    /**
     * <code>VerifiedArea_Pin = 8;</code>
     */
    public static final int VerifiedArea_Pin_VALUE = 8;
    /**
     * <code>VerifiedArea_IsuId = 9;</code>
     */
    public static final int VerifiedArea_IsuId_VALUE = 9;
    /**
     * <code>VerifiedArea_IsuValue = 10;</code>
     */
    public static final int VerifiedArea_IsuValue_VALUE = 10;
    /**
     * <code>VerifiedArea_Multitext = 11;</code>
     */
    public static final int VerifiedArea_Multitext_VALUE = 11;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FujiDisplayArea valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FujiDisplayArea forNumber(int value) {
      switch (value) {
        case 0: return VerifiedArea_Setpoint;
        case 1: return VerifiedArea_IndoorTemp;
        case 2: return VerifiedArea_OutdoorTemp;
        case 3: return VerifiedArea_Humidity;
        case 4: return VerifiedArea_Time;
        case 5: return VerifiedArea_Date_Year;
        case 6: return VerifiedArea_Date_Day;
        case 7: return VerifiedArea_InstallerTest_Stage;
        case 8: return VerifiedArea_Pin;
        case 9: return VerifiedArea_IsuId;
        case 10: return VerifiedArea_IsuValue;
        case 11: return VerifiedArea_Multitext;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FujiDisplayArea>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FujiDisplayArea> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FujiDisplayArea>() {
            public FujiDisplayArea findValueByNumber(int number) {
              return FujiDisplayArea.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final FujiDisplayArea[] VALUES = values();

    public static FujiDisplayArea valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FujiDisplayArea(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.FujiDisplayTextMsg.FujiDisplayArea)
  }

  public static final int DISPLAYAREA_FIELD_NUMBER = 1;
  private int displayArea_ = 0;
  /**
   * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
   * @return The enum numeric value on the wire for displayArea.
   */
  @java.lang.Override public int getDisplayAreaValue() {
    return displayArea_;
  }
  /**
   * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
   * @return The displayArea.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea getDisplayArea() {
    com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea result = com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea.forNumber(displayArea_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (displayArea_ != com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea.VerifiedArea_Setpoint.getNumber()) {
      output.writeEnum(1, displayArea_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (displayArea_ != com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea.VerifiedArea_Setpoint.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, displayArea_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg other = (com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg) obj;

    if (displayArea_ != other.displayArea_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DISPLAYAREA_FIELD_NUMBER;
    hash = (53 * hash) + displayArea_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.FujiDisplayTextMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.FujiDisplayTextMsg)
      com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_FujiDisplayTextMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_FujiDisplayTextMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.class, com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      displayArea_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_FujiDisplayTextMsg_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg build() {
      com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg result = new com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.displayArea_ = displayArea_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.getDefaultInstance()) return this;
      if (other.displayArea_ != 0) {
        setDisplayAreaValue(other.getDisplayAreaValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              displayArea_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int displayArea_ = 0;
    /**
     * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
     * @return The enum numeric value on the wire for displayArea.
     */
    @java.lang.Override public int getDisplayAreaValue() {
      return displayArea_;
    }
    /**
     * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
     * @param value The enum numeric value on the wire for displayArea to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayAreaValue(int value) {
      displayArea_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
     * @return The displayArea.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea getDisplayArea() {
      com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea result = com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea.forNumber(displayArea_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
     * @param value The displayArea to set.
     * @return This builder for chaining.
     */
    public Builder setDisplayArea(com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg.FujiDisplayArea value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      displayArea_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.FujiDisplayTextMsg.FujiDisplayArea displayArea = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDisplayArea() {
      bitField0_ = (bitField0_ & ~0x00000001);
      displayArea_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.FujiDisplayTextMsg)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.FujiDisplayTextMsg)
  private static final com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg();
  }

  public static com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FujiDisplayTextMsg>
      PARSER = new com.google.protobuf.AbstractParser<FujiDisplayTextMsg>() {
    @java.lang.Override
    public FujiDisplayTextMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FujiDisplayTextMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FujiDisplayTextMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.FujiDisplayTextMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

