// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.getISUOption}
 */
public final class getISUOption extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.getISUOption)
    getISUOptionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getISUOption.newBuilder() to construct.
  private getISUOption(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getISUOption() {
    isuOptionList1_ = "";
    isuOptionList2_ = "";
    isuOptionList3_ = "";
    isuOptionList4_ = "";
    isuOptionList5_ = "";
    isuOptionList6_ = "";
    isuOptionList7_ = "";
    isuOptionList8_ = "";
    isuOptionList9_ = "";
    isuOptionList10_ = "";
    status_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new getISUOption();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_getISUOption_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_getISUOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.getISUOption.class, com.resideo.utils.stat.cattgrpccommands.getISUOption.Builder.class);
  }

  public static final int ISUOPTIONLIST1_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList1_ = "";
  /**
   * <code>string isuOptionList1 = 1;</code>
   * @return The isuOptionList1.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList1() {
    java.lang.Object ref = isuOptionList1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList1_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList1 = 1;</code>
   * @return The bytes for isuOptionList1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList1Bytes() {
    java.lang.Object ref = isuOptionList1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST2_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList2_ = "";
  /**
   * <code>string isuOptionList2 = 2;</code>
   * @return The isuOptionList2.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList2() {
    java.lang.Object ref = isuOptionList2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList2_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList2 = 2;</code>
   * @return The bytes for isuOptionList2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList2Bytes() {
    java.lang.Object ref = isuOptionList2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST3_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList3_ = "";
  /**
   * <code>string isuOptionList3 = 3;</code>
   * @return The isuOptionList3.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList3() {
    java.lang.Object ref = isuOptionList3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList3_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList3 = 3;</code>
   * @return The bytes for isuOptionList3.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList3Bytes() {
    java.lang.Object ref = isuOptionList3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST4_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList4_ = "";
  /**
   * <code>string isuOptionList4 = 4;</code>
   * @return The isuOptionList4.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList4() {
    java.lang.Object ref = isuOptionList4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList4_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList4 = 4;</code>
   * @return The bytes for isuOptionList4.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList4Bytes() {
    java.lang.Object ref = isuOptionList4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST5_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList5_ = "";
  /**
   * <code>string isuOptionList5 = 5;</code>
   * @return The isuOptionList5.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList5() {
    java.lang.Object ref = isuOptionList5_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList5_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList5 = 5;</code>
   * @return The bytes for isuOptionList5.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList5Bytes() {
    java.lang.Object ref = isuOptionList5_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList5_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST6_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList6_ = "";
  /**
   * <code>string isuOptionList6 = 6;</code>
   * @return The isuOptionList6.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList6() {
    java.lang.Object ref = isuOptionList6_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList6_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList6 = 6;</code>
   * @return The bytes for isuOptionList6.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList6Bytes() {
    java.lang.Object ref = isuOptionList6_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList6_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST7_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList7_ = "";
  /**
   * <code>string isuOptionList7 = 7;</code>
   * @return The isuOptionList7.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList7() {
    java.lang.Object ref = isuOptionList7_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList7_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList7 = 7;</code>
   * @return The bytes for isuOptionList7.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList7Bytes() {
    java.lang.Object ref = isuOptionList7_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList7_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST8_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList8_ = "";
  /**
   * <code>string isuOptionList8 = 8;</code>
   * @return The isuOptionList8.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList8() {
    java.lang.Object ref = isuOptionList8_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList8_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList8 = 8;</code>
   * @return The bytes for isuOptionList8.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList8Bytes() {
    java.lang.Object ref = isuOptionList8_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList8_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST9_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList9_ = "";
  /**
   * <code>string isuOptionList9 = 9;</code>
   * @return The isuOptionList9.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList9() {
    java.lang.Object ref = isuOptionList9_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList9_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList9 = 9;</code>
   * @return The bytes for isuOptionList9.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList9Bytes() {
    java.lang.Object ref = isuOptionList9_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList9_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLIST10_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isuOptionList10_ = "";
  /**
   * <code>string isuOptionList10 = 10;</code>
   * @return The isuOptionList10.
   */
  @java.lang.Override
  public java.lang.String getIsuOptionList10() {
    java.lang.Object ref = isuOptionList10_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isuOptionList10_ = s;
      return s;
    }
  }
  /**
   * <code>string isuOptionList10 = 10;</code>
   * @return The bytes for isuOptionList10.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsuOptionList10Bytes() {
    java.lang.Object ref = isuOptionList10_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isuOptionList10_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUOPTIONLENGTH_FIELD_NUMBER = 11;
  private int isuOptionLength_ = 0;
  /**
   * <code>int32 isuOptionLength = 11;</code>
   * @return The isuOptionLength.
   */
  @java.lang.Override
  public int getIsuOptionLength() {
    return isuOptionLength_;
  }

  public static final int STATUS_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 12;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 12;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FLAG_FIELD_NUMBER = 13;
  private boolean flag_ = false;
  /**
   * <code>bool flag = 13;</code>
   * @return The flag.
   */
  @java.lang.Override
  public boolean getFlag() {
    return flag_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList1_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, isuOptionList1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList2_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isuOptionList2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList3_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, isuOptionList3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList4_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, isuOptionList4_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList5_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, isuOptionList5_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList6_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, isuOptionList6_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList7_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, isuOptionList7_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList8_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, isuOptionList8_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList9_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, isuOptionList9_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList10_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, isuOptionList10_);
    }
    if (isuOptionLength_ != 0) {
      output.writeInt32(11, isuOptionLength_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, status_);
    }
    if (flag_ != false) {
      output.writeBool(13, flag_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList1_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, isuOptionList1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList2_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isuOptionList2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList3_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, isuOptionList3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList4_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, isuOptionList4_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList5_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, isuOptionList5_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList6_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, isuOptionList6_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList7_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, isuOptionList7_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList8_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, isuOptionList8_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList9_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, isuOptionList9_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isuOptionList10_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, isuOptionList10_);
    }
    if (isuOptionLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, isuOptionLength_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, status_);
    }
    if (flag_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, flag_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.getISUOption)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.getISUOption other = (com.resideo.utils.stat.cattgrpccommands.getISUOption) obj;

    if (!getIsuOptionList1()
        .equals(other.getIsuOptionList1())) return false;
    if (!getIsuOptionList2()
        .equals(other.getIsuOptionList2())) return false;
    if (!getIsuOptionList3()
        .equals(other.getIsuOptionList3())) return false;
    if (!getIsuOptionList4()
        .equals(other.getIsuOptionList4())) return false;
    if (!getIsuOptionList5()
        .equals(other.getIsuOptionList5())) return false;
    if (!getIsuOptionList6()
        .equals(other.getIsuOptionList6())) return false;
    if (!getIsuOptionList7()
        .equals(other.getIsuOptionList7())) return false;
    if (!getIsuOptionList8()
        .equals(other.getIsuOptionList8())) return false;
    if (!getIsuOptionList9()
        .equals(other.getIsuOptionList9())) return false;
    if (!getIsuOptionList10()
        .equals(other.getIsuOptionList10())) return false;
    if (getIsuOptionLength()
        != other.getIsuOptionLength()) return false;
    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (getFlag()
        != other.getFlag()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST1_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList1().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST2_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList2().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST3_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList3().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST4_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList4().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST5_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList5().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST6_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList6().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST7_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList7().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST8_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList8().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST9_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList9().hashCode();
    hash = (37 * hash) + ISUOPTIONLIST10_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionList10().hashCode();
    hash = (37 * hash) + ISUOPTIONLENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getIsuOptionLength();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + FLAG_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFlag());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.getISUOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.getISUOption prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.getISUOption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.getISUOption)
      com.resideo.utils.stat.cattgrpccommands.getISUOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_getISUOption_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_getISUOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.getISUOption.class, com.resideo.utils.stat.cattgrpccommands.getISUOption.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.getISUOption.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isuOptionList1_ = "";
      isuOptionList2_ = "";
      isuOptionList3_ = "";
      isuOptionList4_ = "";
      isuOptionList5_ = "";
      isuOptionList6_ = "";
      isuOptionList7_ = "";
      isuOptionList8_ = "";
      isuOptionList9_ = "";
      isuOptionList10_ = "";
      isuOptionLength_ = 0;
      status_ = "";
      flag_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_getISUOption_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.getISUOption getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.getISUOption.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.getISUOption build() {
      com.resideo.utils.stat.cattgrpccommands.getISUOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.getISUOption buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.getISUOption result = new com.resideo.utils.stat.cattgrpccommands.getISUOption(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.getISUOption result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isuOptionList1_ = isuOptionList1_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isuOptionList2_ = isuOptionList2_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isuOptionList3_ = isuOptionList3_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isuOptionList4_ = isuOptionList4_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.isuOptionList5_ = isuOptionList5_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.isuOptionList6_ = isuOptionList6_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.isuOptionList7_ = isuOptionList7_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.isuOptionList8_ = isuOptionList8_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.isuOptionList9_ = isuOptionList9_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.isuOptionList10_ = isuOptionList10_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.isuOptionLength_ = isuOptionLength_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.flag_ = flag_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.getISUOption) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.getISUOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.getISUOption other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.getISUOption.getDefaultInstance()) return this;
      if (!other.getIsuOptionList1().isEmpty()) {
        isuOptionList1_ = other.isuOptionList1_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getIsuOptionList2().isEmpty()) {
        isuOptionList2_ = other.isuOptionList2_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getIsuOptionList3().isEmpty()) {
        isuOptionList3_ = other.isuOptionList3_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getIsuOptionList4().isEmpty()) {
        isuOptionList4_ = other.isuOptionList4_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getIsuOptionList5().isEmpty()) {
        isuOptionList5_ = other.isuOptionList5_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getIsuOptionList6().isEmpty()) {
        isuOptionList6_ = other.isuOptionList6_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getIsuOptionList7().isEmpty()) {
        isuOptionList7_ = other.isuOptionList7_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getIsuOptionList8().isEmpty()) {
        isuOptionList8_ = other.isuOptionList8_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getIsuOptionList9().isEmpty()) {
        isuOptionList9_ = other.isuOptionList9_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getIsuOptionList10().isEmpty()) {
        isuOptionList10_ = other.isuOptionList10_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (other.getIsuOptionLength() != 0) {
        setIsuOptionLength(other.getIsuOptionLength());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (other.getFlag() != false) {
        setFlag(other.getFlag());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              isuOptionList1_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              isuOptionList2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              isuOptionList3_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              isuOptionList4_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              isuOptionList5_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              isuOptionList6_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              isuOptionList7_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              isuOptionList8_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              isuOptionList9_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              isuOptionList10_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 88: {
              isuOptionLength_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 98: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 104: {
              flag_ = input.readBool();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object isuOptionList1_ = "";
    /**
     * <code>string isuOptionList1 = 1;</code>
     * @return The isuOptionList1.
     */
    public java.lang.String getIsuOptionList1() {
      java.lang.Object ref = isuOptionList1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList1 = 1;</code>
     * @return The bytes for isuOptionList1.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList1Bytes() {
      java.lang.Object ref = isuOptionList1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList1 = 1;</code>
     * @param value The isuOptionList1 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList1(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList1 = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList1() {
      isuOptionList1_ = getDefaultInstance().getIsuOptionList1();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList1 = 1;</code>
     * @param value The bytes for isuOptionList1 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList1_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList2_ = "";
    /**
     * <code>string isuOptionList2 = 2;</code>
     * @return The isuOptionList2.
     */
    public java.lang.String getIsuOptionList2() {
      java.lang.Object ref = isuOptionList2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList2 = 2;</code>
     * @return The bytes for isuOptionList2.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList2Bytes() {
      java.lang.Object ref = isuOptionList2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList2 = 2;</code>
     * @param value The isuOptionList2 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList2(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList2 = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList2() {
      isuOptionList2_ = getDefaultInstance().getIsuOptionList2();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList2 = 2;</code>
     * @param value The bytes for isuOptionList2 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList2_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList3_ = "";
    /**
     * <code>string isuOptionList3 = 3;</code>
     * @return The isuOptionList3.
     */
    public java.lang.String getIsuOptionList3() {
      java.lang.Object ref = isuOptionList3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList3 = 3;</code>
     * @return The bytes for isuOptionList3.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList3Bytes() {
      java.lang.Object ref = isuOptionList3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList3 = 3;</code>
     * @param value The isuOptionList3 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList3(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList3_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList3 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList3() {
      isuOptionList3_ = getDefaultInstance().getIsuOptionList3();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList3 = 3;</code>
     * @param value The bytes for isuOptionList3 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList3_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList4_ = "";
    /**
     * <code>string isuOptionList4 = 4;</code>
     * @return The isuOptionList4.
     */
    public java.lang.String getIsuOptionList4() {
      java.lang.Object ref = isuOptionList4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList4 = 4;</code>
     * @return The bytes for isuOptionList4.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList4Bytes() {
      java.lang.Object ref = isuOptionList4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList4 = 4;</code>
     * @param value The isuOptionList4 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList4(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList4_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList4 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList4() {
      isuOptionList4_ = getDefaultInstance().getIsuOptionList4();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList4 = 4;</code>
     * @param value The bytes for isuOptionList4 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList4_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList5_ = "";
    /**
     * <code>string isuOptionList5 = 5;</code>
     * @return The isuOptionList5.
     */
    public java.lang.String getIsuOptionList5() {
      java.lang.Object ref = isuOptionList5_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList5_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList5 = 5;</code>
     * @return The bytes for isuOptionList5.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList5Bytes() {
      java.lang.Object ref = isuOptionList5_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList5_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList5 = 5;</code>
     * @param value The isuOptionList5 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList5(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList5_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList5 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList5() {
      isuOptionList5_ = getDefaultInstance().getIsuOptionList5();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList5 = 5;</code>
     * @param value The bytes for isuOptionList5 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList5Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList5_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList6_ = "";
    /**
     * <code>string isuOptionList6 = 6;</code>
     * @return The isuOptionList6.
     */
    public java.lang.String getIsuOptionList6() {
      java.lang.Object ref = isuOptionList6_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList6_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList6 = 6;</code>
     * @return The bytes for isuOptionList6.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList6Bytes() {
      java.lang.Object ref = isuOptionList6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList6 = 6;</code>
     * @param value The isuOptionList6 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList6(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList6_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList6 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList6() {
      isuOptionList6_ = getDefaultInstance().getIsuOptionList6();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList6 = 6;</code>
     * @param value The bytes for isuOptionList6 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList6Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList6_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList7_ = "";
    /**
     * <code>string isuOptionList7 = 7;</code>
     * @return The isuOptionList7.
     */
    public java.lang.String getIsuOptionList7() {
      java.lang.Object ref = isuOptionList7_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList7_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList7 = 7;</code>
     * @return The bytes for isuOptionList7.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList7Bytes() {
      java.lang.Object ref = isuOptionList7_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList7_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList7 = 7;</code>
     * @param value The isuOptionList7 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList7(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList7_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList7 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList7() {
      isuOptionList7_ = getDefaultInstance().getIsuOptionList7();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList7 = 7;</code>
     * @param value The bytes for isuOptionList7 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList7Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList7_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList8_ = "";
    /**
     * <code>string isuOptionList8 = 8;</code>
     * @return The isuOptionList8.
     */
    public java.lang.String getIsuOptionList8() {
      java.lang.Object ref = isuOptionList8_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList8_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList8 = 8;</code>
     * @return The bytes for isuOptionList8.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList8Bytes() {
      java.lang.Object ref = isuOptionList8_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList8_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList8 = 8;</code>
     * @param value The isuOptionList8 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList8(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList8_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList8 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList8() {
      isuOptionList8_ = getDefaultInstance().getIsuOptionList8();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList8 = 8;</code>
     * @param value The bytes for isuOptionList8 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList8Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList8_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList9_ = "";
    /**
     * <code>string isuOptionList9 = 9;</code>
     * @return The isuOptionList9.
     */
    public java.lang.String getIsuOptionList9() {
      java.lang.Object ref = isuOptionList9_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList9_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList9 = 9;</code>
     * @return The bytes for isuOptionList9.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList9Bytes() {
      java.lang.Object ref = isuOptionList9_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList9_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList9 = 9;</code>
     * @param value The isuOptionList9 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList9(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList9_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList9 = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList9() {
      isuOptionList9_ = getDefaultInstance().getIsuOptionList9();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList9 = 9;</code>
     * @param value The bytes for isuOptionList9 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList9Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList9_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object isuOptionList10_ = "";
    /**
     * <code>string isuOptionList10 = 10;</code>
     * @return The isuOptionList10.
     */
    public java.lang.String getIsuOptionList10() {
      java.lang.Object ref = isuOptionList10_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isuOptionList10_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isuOptionList10 = 10;</code>
     * @return The bytes for isuOptionList10.
     */
    public com.google.protobuf.ByteString
        getIsuOptionList10Bytes() {
      java.lang.Object ref = isuOptionList10_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isuOptionList10_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isuOptionList10 = 10;</code>
     * @param value The isuOptionList10 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList10(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isuOptionList10_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList10 = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionList10() {
      isuOptionList10_ = getDefaultInstance().getIsuOptionList10();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string isuOptionList10 = 10;</code>
     * @param value The bytes for isuOptionList10 to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionList10Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isuOptionList10_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private int isuOptionLength_ ;
    /**
     * <code>int32 isuOptionLength = 11;</code>
     * @return The isuOptionLength.
     */
    @java.lang.Override
    public int getIsuOptionLength() {
      return isuOptionLength_;
    }
    /**
     * <code>int32 isuOptionLength = 11;</code>
     * @param value The isuOptionLength to set.
     * @return This builder for chaining.
     */
    public Builder setIsuOptionLength(int value) {

      isuOptionLength_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 isuOptionLength = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsuOptionLength() {
      bitField0_ = (bitField0_ & ~0x00000400);
      isuOptionLength_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 12;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 12;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 12;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 12;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private boolean flag_ ;
    /**
     * <code>bool flag = 13;</code>
     * @return The flag.
     */
    @java.lang.Override
    public boolean getFlag() {
      return flag_;
    }
    /**
     * <code>bool flag = 13;</code>
     * @param value The flag to set.
     * @return This builder for chaining.
     */
    public Builder setFlag(boolean value) {

      flag_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>bool flag = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlag() {
      bitField0_ = (bitField0_ & ~0x00001000);
      flag_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.getISUOption)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.getISUOption)
  private static final com.resideo.utils.stat.cattgrpccommands.getISUOption DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.getISUOption();
  }

  public static com.resideo.utils.stat.cattgrpccommands.getISUOption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getISUOption>
      PARSER = new com.google.protobuf.AbstractParser<getISUOption>() {
    @java.lang.Override
    public getISUOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<getISUOption> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getISUOption> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.getISUOption getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

