// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.HumSettingModeMsg}
 */
public final class HumSettingModeMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.HumSettingModeMsg)
    HumSettingModeMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HumSettingModeMsg.newBuilder() to construct.
  private HumSettingModeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HumSettingModeMsg() {
    hummode_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HumSettingModeMsg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_HumSettingModeMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_HumSettingModeMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.class, com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.HumSettingModeMsg.HumMode}
   */
  public enum HumMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HUM_SWITCH_OFF = 0;</code>
     */
    HUM_SWITCH_OFF(0),
    /**
     * <code>HUM_SWITCH_AUTO = 1;</code>
     */
    HUM_SWITCH_AUTO(1),
    /**
     * <code>NUM_HUM_SWITCH = 2;</code>
     */
    NUM_HUM_SWITCH(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>HUM_SWITCH_OFF = 0;</code>
     */
    public static final int HUM_SWITCH_OFF_VALUE = 0;
    /**
     * <code>HUM_SWITCH_AUTO = 1;</code>
     */
    public static final int HUM_SWITCH_AUTO_VALUE = 1;
    /**
     * <code>NUM_HUM_SWITCH = 2;</code>
     */
    public static final int NUM_HUM_SWITCH_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HumMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HumMode forNumber(int value) {
      switch (value) {
        case 0: return HUM_SWITCH_OFF;
        case 1: return HUM_SWITCH_AUTO;
        case 2: return NUM_HUM_SWITCH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HumMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HumMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HumMode>() {
            public HumMode findValueByNumber(int number) {
              return HumMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final HumMode[] VALUES = values();

    public static HumMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HumMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.HumSettingModeMsg.HumMode)
  }

  public static final int SETPOINT_FIELD_NUMBER = 1;
  private float setPoint_ = 0F;
  /**
   * <code>float SetPoint = 1;</code>
   * @return The setPoint.
   */
  @java.lang.Override
  public float getSetPoint() {
    return setPoint_;
  }

  public static final int HUMMODE_FIELD_NUMBER = 2;
  private int hummode_ = 0;
  /**
   * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
   * @return The enum numeric value on the wire for hummode.
   */
  @java.lang.Override public int getHummodeValue() {
    return hummode_;
  }
  /**
   * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
   * @return The hummode.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode getHummode() {
    com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode result = com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode.forNumber(hummode_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode.UNRECOGNIZED : result;
  }

  public static final int WINDOWPROTECTIONLEVEL_FIELD_NUMBER = 3;
  private int windowprotectionlevel_ = 0;
  /**
   * <code>int32 windowprotectionlevel = 3;</code>
   * @return The windowprotectionlevel.
   */
  @java.lang.Override
  public int getWindowprotectionlevel() {
    return windowprotectionlevel_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Float.floatToRawIntBits(setPoint_) != 0) {
      output.writeFloat(1, setPoint_);
    }
    if (hummode_ != com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode.HUM_SWITCH_OFF.getNumber()) {
      output.writeEnum(2, hummode_);
    }
    if (windowprotectionlevel_ != 0) {
      output.writeInt32(3, windowprotectionlevel_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Float.floatToRawIntBits(setPoint_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, setPoint_);
    }
    if (hummode_ != com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode.HUM_SWITCH_OFF.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, hummode_);
    }
    if (windowprotectionlevel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, windowprotectionlevel_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg other = (com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg) obj;

    if (java.lang.Float.floatToIntBits(getSetPoint())
        != java.lang.Float.floatToIntBits(
            other.getSetPoint())) return false;
    if (hummode_ != other.hummode_) return false;
    if (getWindowprotectionlevel()
        != other.getWindowprotectionlevel()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SETPOINT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSetPoint());
    hash = (37 * hash) + HUMMODE_FIELD_NUMBER;
    hash = (53 * hash) + hummode_;
    hash = (37 * hash) + WINDOWPROTECTIONLEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getWindowprotectionlevel();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.HumSettingModeMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.HumSettingModeMsg)
      com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_HumSettingModeMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_HumSettingModeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.class, com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      setPoint_ = 0F;
      hummode_ = 0;
      windowprotectionlevel_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_HumSettingModeMsg_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg build() {
      com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg result = new com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.setPoint_ = setPoint_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.hummode_ = hummode_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.windowprotectionlevel_ = windowprotectionlevel_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.getDefaultInstance()) return this;
      if (other.getSetPoint() != 0F) {
        setSetPoint(other.getSetPoint());
      }
      if (other.hummode_ != 0) {
        setHummodeValue(other.getHummodeValue());
      }
      if (other.getWindowprotectionlevel() != 0) {
        setWindowprotectionlevel(other.getWindowprotectionlevel());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              setPoint_ = input.readFloat();
              bitField0_ |= 0x00000001;
              break;
            } // case 13
            case 16: {
              hummode_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              windowprotectionlevel_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private float setPoint_ ;
    /**
     * <code>float SetPoint = 1;</code>
     * @return The setPoint.
     */
    @java.lang.Override
    public float getSetPoint() {
      return setPoint_;
    }
    /**
     * <code>float SetPoint = 1;</code>
     * @param value The setPoint to set.
     * @return This builder for chaining.
     */
    public Builder setSetPoint(float value) {

      setPoint_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>float SetPoint = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSetPoint() {
      bitField0_ = (bitField0_ & ~0x00000001);
      setPoint_ = 0F;
      onChanged();
      return this;
    }

    private int hummode_ = 0;
    /**
     * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
     * @return The enum numeric value on the wire for hummode.
     */
    @java.lang.Override public int getHummodeValue() {
      return hummode_;
    }
    /**
     * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
     * @param value The enum numeric value on the wire for hummode to set.
     * @return This builder for chaining.
     */
    public Builder setHummodeValue(int value) {
      hummode_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
     * @return The hummode.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode getHummode() {
      com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode result = com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode.forNumber(hummode_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
     * @param value The hummode to set.
     * @return This builder for chaining.
     */
    public Builder setHummode(com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg.HumMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      hummode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.HumSettingModeMsg.HumMode hummode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHummode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      hummode_ = 0;
      onChanged();
      return this;
    }

    private int windowprotectionlevel_ ;
    /**
     * <code>int32 windowprotectionlevel = 3;</code>
     * @return The windowprotectionlevel.
     */
    @java.lang.Override
    public int getWindowprotectionlevel() {
      return windowprotectionlevel_;
    }
    /**
     * <code>int32 windowprotectionlevel = 3;</code>
     * @param value The windowprotectionlevel to set.
     * @return This builder for chaining.
     */
    public Builder setWindowprotectionlevel(int value) {

      windowprotectionlevel_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 windowprotectionlevel = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindowprotectionlevel() {
      bitField0_ = (bitField0_ & ~0x00000004);
      windowprotectionlevel_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.HumSettingModeMsg)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.HumSettingModeMsg)
  private static final com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg();
  }

  public static com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HumSettingModeMsg>
      PARSER = new com.google.protobuf.AbstractParser<HumSettingModeMsg>() {
    @java.lang.Override
    public HumSettingModeMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HumSettingModeMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HumSettingModeMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.HumSettingModeMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

