// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface ISU_OptionSetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.ISU_OptionSet)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GrpcServices.ISU_OptionSet.ISUDevice state = 1;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.GrpcServices.ISU_OptionSet.ISUDevice state = 1;</code>
   * @return The state.
   */
  com.resideo.utils.stat.cattgrpccommands.ISU_OptionSet.ISUDevice getState();

  /**
   * <code>string ISUItem = 2;</code>
   * @return The iSUItem.
   */
  java.lang.String getISUItem();
  /**
   * <code>string ISUItem = 2;</code>
   * @return The bytes for iSUItem.
   */
  com.google.protobuf.ByteString
      getISUItemBytes();

  /**
   * <code>string ISUValue = 3;</code>
   * @return The iSUValue.
   */
  java.lang.String getISUValue();
  /**
   * <code>string ISUValue = 3;</code>
   * @return The bytes for iSUValue.
   */
  com.google.protobuf.ByteString
      getISUValueBytes();

  /**
   * <code>string minValue = 4;</code>
   * @return The minValue.
   */
  java.lang.String getMinValue();
  /**
   * <code>string minValue = 4;</code>
   * @return The bytes for minValue.
   */
  com.google.protobuf.ByteString
      getMinValueBytes();

  /**
   * <code>string maxValue = 5;</code>
   * @return The maxValue.
   */
  java.lang.String getMaxValue();
  /**
   * <code>string maxValue = 5;</code>
   * @return The bytes for maxValue.
   */
  com.google.protobuf.ByteString
      getMaxValueBytes();

  /**
   * <code>int32 totalOptionCount = 6;</code>
   * @return The totalOptionCount.
   */
  int getTotalOptionCount();

  /**
   * <code>string isuNumber_IsuName = 7;</code>
   * @return The isuNumberIsuName.
   */
  java.lang.String getIsuNumberIsuName();
  /**
   * <code>string isuNumber_IsuName = 7;</code>
   * @return The bytes for isuNumberIsuName.
   */
  com.google.protobuf.ByteString
      getIsuNumberIsuNameBytes();
}
