// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.PeriodMessage}
 */
public final class PeriodMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.PeriodMessage)
    PeriodMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PeriodMessage.newBuilder() to construct.
  private PeriodMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PeriodMessage() {
    period_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PeriodMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_PeriodMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_PeriodMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.PeriodMessage.class, com.resideo.utils.stat.cattgrpccommands.PeriodMessage.Builder.class);
  }

  public static final int PERIOD_FIELD_NUMBER = 1;
  private int period_ = 0;
  /**
   * <code>.GrpcServices.E_Periods period = 1;</code>
   * @return The enum numeric value on the wire for period.
   */
  @java.lang.Override public int getPeriodValue() {
    return period_;
  }
  /**
   * <code>.GrpcServices.E_Periods period = 1;</code>
   * @return The period.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.E_Periods getPeriod() {
    com.resideo.utils.stat.cattgrpccommands.E_Periods result = com.resideo.utils.stat.cattgrpccommands.E_Periods.forNumber(period_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.E_Periods.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (period_ != com.resideo.utils.stat.cattgrpccommands.E_Periods.WAKE_EMEA1.getNumber()) {
      output.writeEnum(1, period_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (period_ != com.resideo.utils.stat.cattgrpccommands.E_Periods.WAKE_EMEA1.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, period_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.PeriodMessage)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.PeriodMessage other = (com.resideo.utils.stat.cattgrpccommands.PeriodMessage) obj;

    if (period_ != other.period_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PERIOD_FIELD_NUMBER;
    hash = (53 * hash) + period_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.PeriodMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.PeriodMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.PeriodMessage)
      com.resideo.utils.stat.cattgrpccommands.PeriodMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_PeriodMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_PeriodMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.PeriodMessage.class, com.resideo.utils.stat.cattgrpccommands.PeriodMessage.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.PeriodMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      period_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_PeriodMessage_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.PeriodMessage getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.PeriodMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.PeriodMessage build() {
      com.resideo.utils.stat.cattgrpccommands.PeriodMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.PeriodMessage buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.PeriodMessage result = new com.resideo.utils.stat.cattgrpccommands.PeriodMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.PeriodMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.period_ = period_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.PeriodMessage) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.PeriodMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.PeriodMessage other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.PeriodMessage.getDefaultInstance()) return this;
      if (other.period_ != 0) {
        setPeriodValue(other.getPeriodValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              period_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int period_ = 0;
    /**
     * <code>.GrpcServices.E_Periods period = 1;</code>
     * @return The enum numeric value on the wire for period.
     */
    @java.lang.Override public int getPeriodValue() {
      return period_;
    }
    /**
     * <code>.GrpcServices.E_Periods period = 1;</code>
     * @param value The enum numeric value on the wire for period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodValue(int value) {
      period_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.E_Periods period = 1;</code>
     * @return The period.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.E_Periods getPeriod() {
      com.resideo.utils.stat.cattgrpccommands.E_Periods result = com.resideo.utils.stat.cattgrpccommands.E_Periods.forNumber(period_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.E_Periods.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.E_Periods period = 1;</code>
     * @param value The period to set.
     * @return This builder for chaining.
     */
    public Builder setPeriod(com.resideo.utils.stat.cattgrpccommands.E_Periods value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      period_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.E_Periods period = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriod() {
      bitField0_ = (bitField0_ & ~0x00000001);
      period_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.PeriodMessage)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.PeriodMessage)
  private static final com.resideo.utils.stat.cattgrpccommands.PeriodMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.PeriodMessage();
  }

  public static com.resideo.utils.stat.cattgrpccommands.PeriodMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PeriodMessage>
      PARSER = new com.google.protobuf.AbstractParser<PeriodMessage>() {
    @java.lang.Override
    public PeriodMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PeriodMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PeriodMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.PeriodMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

