// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface PhysicalRelayMsg_FJOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.PhysicalRelayMsg_FJ)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .GrpcServices.PhysicalRelayMsg_FJ.Relays relay = 1;</code>
   * @return A list containing the relay.
   */
  java.util.List<com.resideo.utils.stat.cattgrpccommands.PhysicalRelayMsg_FJ.Relays> getRelayList();
  /**
   * <code>repeated .GrpcServices.PhysicalRelayMsg_FJ.Relays relay = 1;</code>
   * @return The count of relay.
   */
  int getRelayCount();
  /**
   * <code>repeated .GrpcServices.PhysicalRelayMsg_FJ.Relays relay = 1;</code>
   * @param index The index of the element to return.
   * @return The relay at the given index.
   */
  com.resideo.utils.stat.cattgrpccommands.PhysicalRelayMsg_FJ.Relays getRelay(int index);
  /**
   * <code>repeated .GrpcServices.PhysicalRelayMsg_FJ.Relays relay = 1;</code>
   * @return A list containing the enum numeric values on the wire for relay.
   */
  java.util.List<java.lang.Integer>
  getRelayValueList();
  /**
   * <code>repeated .GrpcServices.PhysicalRelayMsg_FJ.Relays relay = 1;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of relay at the given index.
   */
  int getRelayValue(int index);
}
