// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface RESET_SCHEDULEOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.RESET_SCHEDULE)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GrpcServices.RESET_SCHEDULE.Reset_from_WhichScreen screenName = 1;</code>
   * @return The enum numeric value on the wire for screenName.
   */
  int getScreenNameValue();
  /**
   * <code>.GrpcServices.RESET_SCHEDULE.Reset_from_WhichScreen screenName = 1;</code>
   * @return The screenName.
   */
  com.resideo.utils.stat.cattgrpccommands.RESET_SCHEDULE.Reset_from_WhichScreen getScreenName();

  /**
   * <code>.GrpcServices.RESET_SCHEDULE.resetAction actionName = 2;</code>
   * @return The enum numeric value on the wire for actionName.
   */
  int getActionNameValue();
  /**
   * <code>.GrpcServices.RESET_SCHEDULE.resetAction actionName = 2;</code>
   * @return The actionName.
   */
  com.resideo.utils.stat.cattgrpccommands.RESET_SCHEDULE.resetAction getActionName();

  /**
   * <code>string status = 3;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>bool flag = 4;</code>
   * @return The flag.
   */
  boolean getFlag();
}
