// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface SET_SCHEDULEOPTIONSOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.SET_SCHEDULEOPTIONS)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GrpcServices.SET_SCHEDULEOPTIONS.enable_Disable update = 1;</code>
   * @return The enum numeric value on the wire for update.
   */
  int getUpdateValue();
  /**
   * <code>.GrpcServices.SET_SCHEDULEOPTIONS.enable_Disable update = 1;</code>
   * @return The update.
   */
  com.resideo.utils.stat.cattgrpccommands.SET_SCHEDULEOPTIONS.enable_Disable getUpdate();
}
