// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface SetPointMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.SetPointMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float val = 1;</code>
   * @return The val.
   */
  float getVal();

  /**
   * <code>.GrpcServices.SetPointMsg.SetPoint type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.GrpcServices.SetPointMsg.SetPoint type = 2;</code>
   * @return The type.
   */
  com.resideo.utils.stat.cattgrpccommands.SetPointMsg.SetPoint getType();
}
