// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.setScreenShotFolder}
 */
public final class setScreenShotFolder extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.setScreenShotFolder)
    setScreenShotFolderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use setScreenShotFolder.newBuilder() to construct.
  private setScreenShotFolder(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private setScreenShotFolder() {
    screenShotFolderPath_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new setScreenShotFolder();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_setScreenShotFolder_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_setScreenShotFolder_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.class, com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.Builder.class);
  }

  public static final int SCREENSHOTFOLDERPATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object screenShotFolderPath_ = "";
  /**
   * <code>string screenShotFolderPath = 1;</code>
   * @return The screenShotFolderPath.
   */
  @java.lang.Override
  public java.lang.String getScreenShotFolderPath() {
    java.lang.Object ref = screenShotFolderPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      screenShotFolderPath_ = s;
      return s;
    }
  }
  /**
   * <code>string screenShotFolderPath = 1;</code>
   * @return The bytes for screenShotFolderPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScreenShotFolderPathBytes() {
    java.lang.Object ref = screenShotFolderPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      screenShotFolderPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(screenShotFolderPath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, screenShotFolderPath_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(screenShotFolderPath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, screenShotFolderPath_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder other = (com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder) obj;

    if (!getScreenShotFolderPath()
        .equals(other.getScreenShotFolderPath())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCREENSHOTFOLDERPATH_FIELD_NUMBER;
    hash = (53 * hash) + getScreenShotFolderPath().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.setScreenShotFolder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.setScreenShotFolder)
      com.resideo.utils.stat.cattgrpccommands.setScreenShotFolderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_setScreenShotFolder_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_setScreenShotFolder_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.class, com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      screenShotFolderPath_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_setScreenShotFolder_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder build() {
      com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder result = new com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.screenShotFolderPath_ = screenShotFolderPath_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder.getDefaultInstance()) return this;
      if (!other.getScreenShotFolderPath().isEmpty()) {
        screenShotFolderPath_ = other.screenShotFolderPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              screenShotFolderPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object screenShotFolderPath_ = "";
    /**
     * <code>string screenShotFolderPath = 1;</code>
     * @return The screenShotFolderPath.
     */
    public java.lang.String getScreenShotFolderPath() {
      java.lang.Object ref = screenShotFolderPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        screenShotFolderPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string screenShotFolderPath = 1;</code>
     * @return The bytes for screenShotFolderPath.
     */
    public com.google.protobuf.ByteString
        getScreenShotFolderPathBytes() {
      java.lang.Object ref = screenShotFolderPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        screenShotFolderPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string screenShotFolderPath = 1;</code>
     * @param value The screenShotFolderPath to set.
     * @return This builder for chaining.
     */
    public Builder setScreenShotFolderPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      screenShotFolderPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string screenShotFolderPath = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScreenShotFolderPath() {
      screenShotFolderPath_ = getDefaultInstance().getScreenShotFolderPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string screenShotFolderPath = 1;</code>
     * @param value The bytes for screenShotFolderPath to set.
     * @return This builder for chaining.
     */
    public Builder setScreenShotFolderPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      screenShotFolderPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.setScreenShotFolder)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.setScreenShotFolder)
  private static final com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder();
  }

  public static com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<setScreenShotFolder>
      PARSER = new com.google.protobuf.AbstractParser<setScreenShotFolder>() {
    @java.lang.Override
    public setScreenShotFolder parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<setScreenShotFolder> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<setScreenShotFolder> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.setScreenShotFolder getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

