// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface Stat_ResetUIOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.Stat_ResetUI)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.GrpcServices.Stat_ResetUI.ResetMode reset_mode = 1;</code>
   * @return The enum numeric value on the wire for resetMode.
   */
  int getResetModeValue();
  /**
   * <code>.GrpcServices.Stat_ResetUI.ResetMode reset_mode = 1;</code>
   * @return The resetMode.
   */
  com.resideo.utils.stat.cattgrpccommands.Stat_ResetUI.ResetMode getResetMode();
}
