// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.Stat_Reset_FJ}
 */
public final class Stat_Reset_FJ extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.Stat_Reset_FJ)
    Stat_Reset_FJOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Stat_Reset_FJ.newBuilder() to construct.
  private Stat_Reset_FJ(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Stat_Reset_FJ() {
    resetMode_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Stat_Reset_FJ();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Stat_Reset_FJ_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Stat_Reset_FJ_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.class, com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.Stat_Reset_FJ.ResetMode}
   */
  public enum ResetMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>AAT_SYSTEM_RESET_DEFAULT_NVM = 0;</code>
     */
    AAT_SYSTEM_RESET_DEFAULT_NVM(0),
    /**
     * <code>AAT_SYSTEM_RESET_PRESERVE_NVM = 1;</code>
     */
    AAT_SYSTEM_RESET_PRESERVE_NVM(1),
    /**
     * <code>AAT_WATCHDOG_RESET_PRESERVE_NVM = 2;</code>
     */
    AAT_WATCHDOG_RESET_PRESERVE_NVM(2),
    /**
     * <code>AAT_WATCHDOG_RESET_RADIO = 3;</code>
     */
    AAT_WATCHDOG_RESET_RADIO(3),
    /**
     * <code>AAT_FACTORY_RESET = 4;</code>
     */
    AAT_FACTORY_RESET(4),
    /**
     * <code>AAT_FACTORY_RESET_TSTAT = 5;</code>
     */
    AAT_FACTORY_RESET_TSTAT(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AAT_SYSTEM_RESET_DEFAULT_NVM = 0;</code>
     */
    public static final int AAT_SYSTEM_RESET_DEFAULT_NVM_VALUE = 0;
    /**
     * <code>AAT_SYSTEM_RESET_PRESERVE_NVM = 1;</code>
     */
    public static final int AAT_SYSTEM_RESET_PRESERVE_NVM_VALUE = 1;
    /**
     * <code>AAT_WATCHDOG_RESET_PRESERVE_NVM = 2;</code>
     */
    public static final int AAT_WATCHDOG_RESET_PRESERVE_NVM_VALUE = 2;
    /**
     * <code>AAT_WATCHDOG_RESET_RADIO = 3;</code>
     */
    public static final int AAT_WATCHDOG_RESET_RADIO_VALUE = 3;
    /**
     * <code>AAT_FACTORY_RESET = 4;</code>
     */
    public static final int AAT_FACTORY_RESET_VALUE = 4;
    /**
     * <code>AAT_FACTORY_RESET_TSTAT = 5;</code>
     */
    public static final int AAT_FACTORY_RESET_TSTAT_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResetMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResetMode forNumber(int value) {
      switch (value) {
        case 0: return AAT_SYSTEM_RESET_DEFAULT_NVM;
        case 1: return AAT_SYSTEM_RESET_PRESERVE_NVM;
        case 2: return AAT_WATCHDOG_RESET_PRESERVE_NVM;
        case 3: return AAT_WATCHDOG_RESET_RADIO;
        case 4: return AAT_FACTORY_RESET;
        case 5: return AAT_FACTORY_RESET_TSTAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResetMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResetMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResetMode>() {
            public ResetMode findValueByNumber(int number) {
              return ResetMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResetMode[] VALUES = values();

    public static ResetMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResetMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.Stat_Reset_FJ.ResetMode)
  }

  public static final int RESET_MODE_FIELD_NUMBER = 1;
  private int resetMode_ = 0;
  /**
   * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
   * @return The enum numeric value on the wire for resetMode.
   */
  @java.lang.Override public int getResetModeValue() {
    return resetMode_;
  }
  /**
   * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
   * @return The resetMode.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode getResetMode() {
    com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode result = com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode.forNumber(resetMode_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (resetMode_ != com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode.AAT_SYSTEM_RESET_DEFAULT_NVM.getNumber()) {
      output.writeEnum(1, resetMode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (resetMode_ != com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode.AAT_SYSTEM_RESET_DEFAULT_NVM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, resetMode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ other = (com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ) obj;

    if (resetMode_ != other.resetMode_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESET_MODE_FIELD_NUMBER;
    hash = (53 * hash) + resetMode_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.Stat_Reset_FJ}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.Stat_Reset_FJ)
      com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Stat_Reset_FJ_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Stat_Reset_FJ_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.class, com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      resetMode_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Stat_Reset_FJ_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ build() {
      com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ result = new com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.resetMode_ = resetMode_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.getDefaultInstance()) return this;
      if (other.resetMode_ != 0) {
        setResetModeValue(other.getResetModeValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              resetMode_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int resetMode_ = 0;
    /**
     * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
     * @return The enum numeric value on the wire for resetMode.
     */
    @java.lang.Override public int getResetModeValue() {
      return resetMode_;
    }
    /**
     * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
     * @param value The enum numeric value on the wire for resetMode to set.
     * @return This builder for chaining.
     */
    public Builder setResetModeValue(int value) {
      resetMode_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
     * @return The resetMode.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode getResetMode() {
      com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode result = com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode.forNumber(resetMode_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
     * @param value The resetMode to set.
     * @return This builder for chaining.
     */
    public Builder setResetMode(com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ.ResetMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      resetMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.Stat_Reset_FJ.ResetMode reset_mode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResetMode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      resetMode_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.Stat_Reset_FJ)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.Stat_Reset_FJ)
  private static final com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ();
  }

  public static com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Stat_Reset_FJ>
      PARSER = new com.google.protobuf.AbstractParser<Stat_Reset_FJ>() {
    @java.lang.Override
    public Stat_Reset_FJ parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Stat_Reset_FJ> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Stat_Reset_FJ> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.Stat_Reset_FJ getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

