// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

public interface Stat_SetRoomNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcServices.Stat_SetRoomName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Room_Name = 1;</code>
   * @return The roomName.
   */
  java.lang.String getRoomName();
  /**
   * <code>string Room_Name = 1;</code>
   * @return The bytes for roomName.
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>int32 Room_ID = 2;</code>
   * @return The roomID.
   */
  int getRoomID();
}
