// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.VacationHoldMsg}
 */
public final class VacationHoldMsg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.VacationHoldMsg)
    VacationHoldMsgOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VacationHoldMsg.newBuilder() to construct.
  private VacationHoldMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VacationHoldMsg() {
    startTime_ = "";
    endTime_ = "";
    fansw_ = 0;
    prioritymode_ = 0;
    startTimeMilliSeconds_ = "";
    endTimeMilliSeconds_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VacationHoldMsg();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_VacationHoldMsg_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_VacationHoldMsg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.class, com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.Builder.class);
  }

  /**
   * Protobuf enum {@code GrpcServices.VacationHoldMsg.FanSw}
   */
  public enum FanSw
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ON = 0;</code>
     */
    ON(0),
    /**
     * <code>AUTO = 1;</code>
     */
    AUTO(1),
    /**
     * <code>CIRCULATE = 2;</code>
     */
    CIRCULATE(2),
    /**
     * <code>SCHED = 3;</code>
     */
    SCHED(3),
    /**
     * <code>OFF = 4;</code>
     */
    OFF(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ON = 0;</code>
     */
    public static final int ON_VALUE = 0;
    /**
     * <code>AUTO = 1;</code>
     */
    public static final int AUTO_VALUE = 1;
    /**
     * <code>CIRCULATE = 2;</code>
     */
    public static final int CIRCULATE_VALUE = 2;
    /**
     * <code>SCHED = 3;</code>
     */
    public static final int SCHED_VALUE = 3;
    /**
     * <code>OFF = 4;</code>
     */
    public static final int OFF_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FanSw valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FanSw forNumber(int value) {
      switch (value) {
        case 0: return ON;
        case 1: return AUTO;
        case 2: return CIRCULATE;
        case 3: return SCHED;
        case 4: return OFF;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FanSw>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FanSw> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FanSw>() {
            public FanSw findValueByNumber(int number) {
              return FanSw.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final FanSw[] VALUES = values();

    public static FanSw valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FanSw(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.VacationHoldMsg.FanSw)
  }

  /**
   * Protobuf enum {@code GrpcServices.VacationHoldMsg.PriorityMode}
   */
  public enum PriorityMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PICK_A_ROOM = 0;</code>
     */
    PICK_A_ROOM(0),
    /**
     * <code>FOLLOW_ME = 1;</code>
     */
    FOLLOW_ME(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PICK_A_ROOM = 0;</code>
     */
    public static final int PICK_A_ROOM_VALUE = 0;
    /**
     * <code>FOLLOW_ME = 1;</code>
     */
    public static final int FOLLOW_ME_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PriorityMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PriorityMode forNumber(int value) {
      switch (value) {
        case 0: return PICK_A_ROOM;
        case 1: return FOLLOW_ME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PriorityMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PriorityMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PriorityMode>() {
            public PriorityMode findValueByNumber(int number) {
              return PriorityMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.getDescriptor().getEnumTypes().get(1);
    }

    private static final PriorityMode[] VALUES = values();

    public static PriorityMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PriorityMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GrpcServices.VacationHoldMsg.PriorityMode)
  }

  public static final int ISACTIVE_FIELD_NUMBER = 1;
  private boolean isActive_ = false;
  /**
   * <code>bool IsActive = 1;</code>
   * @return The isActive.
   */
  @java.lang.Override
  public boolean getIsActive() {
    return isActive_;
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object startTime_ = "";
  /**
   * <code>string StartTime = 2;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public java.lang.String getStartTime() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startTime_ = s;
      return s;
    }
  }
  /**
   * <code>string StartTime = 2;</code>
   * @return The bytes for startTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartTimeBytes() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDTIME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object endTime_ = "";
  /**
   * <code>string EndTime = 3;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public java.lang.String getEndTime() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endTime_ = s;
      return s;
    }
  }
  /**
   * <code>string EndTime = 3;</code>
   * @return The bytes for endTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndTimeBytes() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEATSP_FIELD_NUMBER = 4;
  private float heatSP_ = 0F;
  /**
   * <code>float HeatSP = 4;</code>
   * @return The heatSP.
   */
  @java.lang.Override
  public float getHeatSP() {
    return heatSP_;
  }

  public static final int COOLSP_FIELD_NUMBER = 5;
  private float coolSP_ = 0F;
  /**
   * <code>float CoolSP = 5;</code>
   * @return The coolSP.
   */
  @java.lang.Override
  public float getCoolSP() {
    return coolSP_;
  }

  public static final int FANSW_FIELD_NUMBER = 6;
  private int fansw_ = 0;
  /**
   * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
   * @return The enum numeric value on the wire for fansw.
   */
  @java.lang.Override public int getFanswValue() {
    return fansw_;
  }
  /**
   * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
   * @return The fansw.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw getFansw() {
    com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw result = com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw.forNumber(fansw_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw.UNRECOGNIZED : result;
  }

  public static final int PRIORITYMODE_FIELD_NUMBER = 7;
  private int prioritymode_ = 0;
  /**
   * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
   * @return The enum numeric value on the wire for prioritymode.
   */
  @java.lang.Override public int getPrioritymodeValue() {
    return prioritymode_;
  }
  /**
   * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
   * @return The prioritymode.
   */
  @java.lang.Override public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode getPrioritymode() {
    com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode result = com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode.forNumber(prioritymode_);
    return result == null ? com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode.UNRECOGNIZED : result;
  }

  public static final int PICKEDROOMS_FIELD_NUMBER = 8;
  private int pickedRooms_ = 0;
  /**
   * <code>int32 PickedRooms = 8;</code>
   * @return The pickedRooms.
   */
  @java.lang.Override
  public int getPickedRooms() {
    return pickedRooms_;
  }

  public static final int STARTTIME_MILLISECONDS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object startTimeMilliSeconds_ = "";
  /**
   * <code>string StartTime_milliSeconds = 9;</code>
   * @return The startTimeMilliSeconds.
   */
  @java.lang.Override
  public java.lang.String getStartTimeMilliSeconds() {
    java.lang.Object ref = startTimeMilliSeconds_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startTimeMilliSeconds_ = s;
      return s;
    }
  }
  /**
   * <code>string StartTime_milliSeconds = 9;</code>
   * @return The bytes for startTimeMilliSeconds.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartTimeMilliSecondsBytes() {
    java.lang.Object ref = startTimeMilliSeconds_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startTimeMilliSeconds_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDTIME_MILLISECONDS_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object endTimeMilliSeconds_ = "";
  /**
   * <code>string EndTime_milliSeconds = 10;</code>
   * @return The endTimeMilliSeconds.
   */
  @java.lang.Override
  public java.lang.String getEndTimeMilliSeconds() {
    java.lang.Object ref = endTimeMilliSeconds_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endTimeMilliSeconds_ = s;
      return s;
    }
  }
  /**
   * <code>string EndTime_milliSeconds = 10;</code>
   * @return The bytes for endTimeMilliSeconds.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEndTimeMilliSecondsBytes() {
    java.lang.Object ref = endTimeMilliSeconds_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endTimeMilliSeconds_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isActive_ != false) {
      output.writeBool(1, isActive_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, startTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, endTime_);
    }
    if (java.lang.Float.floatToRawIntBits(heatSP_) != 0) {
      output.writeFloat(4, heatSP_);
    }
    if (java.lang.Float.floatToRawIntBits(coolSP_) != 0) {
      output.writeFloat(5, coolSP_);
    }
    if (fansw_ != com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw.ON.getNumber()) {
      output.writeEnum(6, fansw_);
    }
    if (prioritymode_ != com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode.PICK_A_ROOM.getNumber()) {
      output.writeEnum(7, prioritymode_);
    }
    if (pickedRooms_ != 0) {
      output.writeInt32(8, pickedRooms_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTimeMilliSeconds_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, startTimeMilliSeconds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTimeMilliSeconds_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, endTimeMilliSeconds_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isActive_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isActive_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, startTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, endTime_);
    }
    if (java.lang.Float.floatToRawIntBits(heatSP_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, heatSP_);
    }
    if (java.lang.Float.floatToRawIntBits(coolSP_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, coolSP_);
    }
    if (fansw_ != com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw.ON.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, fansw_);
    }
    if (prioritymode_ != com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode.PICK_A_ROOM.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, prioritymode_);
    }
    if (pickedRooms_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, pickedRooms_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startTimeMilliSeconds_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, startTimeMilliSeconds_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endTimeMilliSeconds_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, endTimeMilliSeconds_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg other = (com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg) obj;

    if (getIsActive()
        != other.getIsActive()) return false;
    if (!getStartTime()
        .equals(other.getStartTime())) return false;
    if (!getEndTime()
        .equals(other.getEndTime())) return false;
    if (java.lang.Float.floatToIntBits(getHeatSP())
        != java.lang.Float.floatToIntBits(
            other.getHeatSP())) return false;
    if (java.lang.Float.floatToIntBits(getCoolSP())
        != java.lang.Float.floatToIntBits(
            other.getCoolSP())) return false;
    if (fansw_ != other.fansw_) return false;
    if (prioritymode_ != other.prioritymode_) return false;
    if (getPickedRooms()
        != other.getPickedRooms()) return false;
    if (!getStartTimeMilliSeconds()
        .equals(other.getStartTimeMilliSeconds())) return false;
    if (!getEndTimeMilliSeconds()
        .equals(other.getEndTimeMilliSeconds())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsActive());
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getStartTime().hashCode();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getEndTime().hashCode();
    hash = (37 * hash) + HEATSP_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getHeatSP());
    hash = (37 * hash) + COOLSP_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getCoolSP());
    hash = (37 * hash) + FANSW_FIELD_NUMBER;
    hash = (53 * hash) + fansw_;
    hash = (37 * hash) + PRIORITYMODE_FIELD_NUMBER;
    hash = (53 * hash) + prioritymode_;
    hash = (37 * hash) + PICKEDROOMS_FIELD_NUMBER;
    hash = (53 * hash) + getPickedRooms();
    hash = (37 * hash) + STARTTIME_MILLISECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getStartTimeMilliSeconds().hashCode();
    hash = (37 * hash) + ENDTIME_MILLISECONDS_FIELD_NUMBER;
    hash = (53 * hash) + getEndTimeMilliSeconds().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.VacationHoldMsg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.VacationHoldMsg)
      com.resideo.utils.stat.cattgrpccommands.VacationHoldMsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_VacationHoldMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_VacationHoldMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.class, com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isActive_ = false;
      startTime_ = "";
      endTime_ = "";
      heatSP_ = 0F;
      coolSP_ = 0F;
      fansw_ = 0;
      prioritymode_ = 0;
      pickedRooms_ = 0;
      startTimeMilliSeconds_ = "";
      endTimeMilliSeconds_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_VacationHoldMsg_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg build() {
      com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg result = new com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isActive_ = isActive_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.endTime_ = endTime_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.heatSP_ = heatSP_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.coolSP_ = coolSP_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.fansw_ = fansw_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.prioritymode_ = prioritymode_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.pickedRooms_ = pickedRooms_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.startTimeMilliSeconds_ = startTimeMilliSeconds_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.endTimeMilliSeconds_ = endTimeMilliSeconds_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.getDefaultInstance()) return this;
      if (other.getIsActive() != false) {
        setIsActive(other.getIsActive());
      }
      if (!other.getStartTime().isEmpty()) {
        startTime_ = other.startTime_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getEndTime().isEmpty()) {
        endTime_ = other.endTime_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getHeatSP() != 0F) {
        setHeatSP(other.getHeatSP());
      }
      if (other.getCoolSP() != 0F) {
        setCoolSP(other.getCoolSP());
      }
      if (other.fansw_ != 0) {
        setFanswValue(other.getFanswValue());
      }
      if (other.prioritymode_ != 0) {
        setPrioritymodeValue(other.getPrioritymodeValue());
      }
      if (other.getPickedRooms() != 0) {
        setPickedRooms(other.getPickedRooms());
      }
      if (!other.getStartTimeMilliSeconds().isEmpty()) {
        startTimeMilliSeconds_ = other.startTimeMilliSeconds_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getEndTimeMilliSeconds().isEmpty()) {
        endTimeMilliSeconds_ = other.endTimeMilliSeconds_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isActive_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              startTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              endTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 37: {
              heatSP_ = input.readFloat();
              bitField0_ |= 0x00000008;
              break;
            } // case 37
            case 45: {
              coolSP_ = input.readFloat();
              bitField0_ |= 0x00000010;
              break;
            } // case 45
            case 48: {
              fansw_ = input.readEnum();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              prioritymode_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              pickedRooms_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              startTimeMilliSeconds_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              endTimeMilliSeconds_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isActive_ ;
    /**
     * <code>bool IsActive = 1;</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }
    /**
     * <code>bool IsActive = 1;</code>
     * @param value The isActive to set.
     * @return This builder for chaining.
     */
    public Builder setIsActive(boolean value) {

      isActive_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool IsActive = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsActive() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isActive_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object startTime_ = "";
    /**
     * <code>string StartTime = 2;</code>
     * @return The startTime.
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string StartTime = 2;</code>
     * @return The bytes for startTime.
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string StartTime = 2;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      startTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string StartTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      startTime_ = getDefaultInstance().getStartTime();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string StartTime = 2;</code>
     * @param value The bytes for startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      startTime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object endTime_ = "";
    /**
     * <code>string EndTime = 3;</code>
     * @return The endTime.
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string EndTime = 3;</code>
     * @return The bytes for endTime.
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string EndTime = 3;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      endTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string EndTime = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      endTime_ = getDefaultInstance().getEndTime();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string EndTime = 3;</code>
     * @param value The bytes for endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      endTime_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private float heatSP_ ;
    /**
     * <code>float HeatSP = 4;</code>
     * @return The heatSP.
     */
    @java.lang.Override
    public float getHeatSP() {
      return heatSP_;
    }
    /**
     * <code>float HeatSP = 4;</code>
     * @param value The heatSP to set.
     * @return This builder for chaining.
     */
    public Builder setHeatSP(float value) {

      heatSP_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>float HeatSP = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeatSP() {
      bitField0_ = (bitField0_ & ~0x00000008);
      heatSP_ = 0F;
      onChanged();
      return this;
    }

    private float coolSP_ ;
    /**
     * <code>float CoolSP = 5;</code>
     * @return The coolSP.
     */
    @java.lang.Override
    public float getCoolSP() {
      return coolSP_;
    }
    /**
     * <code>float CoolSP = 5;</code>
     * @param value The coolSP to set.
     * @return This builder for chaining.
     */
    public Builder setCoolSP(float value) {

      coolSP_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>float CoolSP = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoolSP() {
      bitField0_ = (bitField0_ & ~0x00000010);
      coolSP_ = 0F;
      onChanged();
      return this;
    }

    private int fansw_ = 0;
    /**
     * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
     * @return The enum numeric value on the wire for fansw.
     */
    @java.lang.Override public int getFanswValue() {
      return fansw_;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
     * @param value The enum numeric value on the wire for fansw to set.
     * @return This builder for chaining.
     */
    public Builder setFanswValue(int value) {
      fansw_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
     * @return The fansw.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw getFansw() {
      com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw result = com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw.forNumber(fansw_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
     * @param value The fansw to set.
     * @return This builder for chaining.
     */
    public Builder setFansw(com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.FanSw value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      fansw_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.FanSw fansw = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFansw() {
      bitField0_ = (bitField0_ & ~0x00000020);
      fansw_ = 0;
      onChanged();
      return this;
    }

    private int prioritymode_ = 0;
    /**
     * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
     * @return The enum numeric value on the wire for prioritymode.
     */
    @java.lang.Override public int getPrioritymodeValue() {
      return prioritymode_;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
     * @param value The enum numeric value on the wire for prioritymode to set.
     * @return This builder for chaining.
     */
    public Builder setPrioritymodeValue(int value) {
      prioritymode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
     * @return The prioritymode.
     */
    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode getPrioritymode() {
      com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode result = com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode.forNumber(prioritymode_);
      return result == null ? com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode.UNRECOGNIZED : result;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
     * @param value The prioritymode to set.
     * @return This builder for chaining.
     */
    public Builder setPrioritymode(com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg.PriorityMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      prioritymode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.GrpcServices.VacationHoldMsg.PriorityMode prioritymode = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrioritymode() {
      bitField0_ = (bitField0_ & ~0x00000040);
      prioritymode_ = 0;
      onChanged();
      return this;
    }

    private int pickedRooms_ ;
    /**
     * <code>int32 PickedRooms = 8;</code>
     * @return The pickedRooms.
     */
    @java.lang.Override
    public int getPickedRooms() {
      return pickedRooms_;
    }
    /**
     * <code>int32 PickedRooms = 8;</code>
     * @param value The pickedRooms to set.
     * @return This builder for chaining.
     */
    public Builder setPickedRooms(int value) {

      pickedRooms_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 PickedRooms = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPickedRooms() {
      bitField0_ = (bitField0_ & ~0x00000080);
      pickedRooms_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object startTimeMilliSeconds_ = "";
    /**
     * <code>string StartTime_milliSeconds = 9;</code>
     * @return The startTimeMilliSeconds.
     */
    public java.lang.String getStartTimeMilliSeconds() {
      java.lang.Object ref = startTimeMilliSeconds_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTimeMilliSeconds_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string StartTime_milliSeconds = 9;</code>
     * @return The bytes for startTimeMilliSeconds.
     */
    public com.google.protobuf.ByteString
        getStartTimeMilliSecondsBytes() {
      java.lang.Object ref = startTimeMilliSeconds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTimeMilliSeconds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string StartTime_milliSeconds = 9;</code>
     * @param value The startTimeMilliSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeMilliSeconds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      startTimeMilliSeconds_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string StartTime_milliSeconds = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTimeMilliSeconds() {
      startTimeMilliSeconds_ = getDefaultInstance().getStartTimeMilliSeconds();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string StartTime_milliSeconds = 9;</code>
     * @param value The bytes for startTimeMilliSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeMilliSecondsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      startTimeMilliSeconds_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object endTimeMilliSeconds_ = "";
    /**
     * <code>string EndTime_milliSeconds = 10;</code>
     * @return The endTimeMilliSeconds.
     */
    public java.lang.String getEndTimeMilliSeconds() {
      java.lang.Object ref = endTimeMilliSeconds_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTimeMilliSeconds_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string EndTime_milliSeconds = 10;</code>
     * @return The bytes for endTimeMilliSeconds.
     */
    public com.google.protobuf.ByteString
        getEndTimeMilliSecondsBytes() {
      java.lang.Object ref = endTimeMilliSeconds_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTimeMilliSeconds_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string EndTime_milliSeconds = 10;</code>
     * @param value The endTimeMilliSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeMilliSeconds(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      endTimeMilliSeconds_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string EndTime_milliSeconds = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTimeMilliSeconds() {
      endTimeMilliSeconds_ = getDefaultInstance().getEndTimeMilliSeconds();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string EndTime_milliSeconds = 10;</code>
     * @param value The bytes for endTimeMilliSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeMilliSecondsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      endTimeMilliSeconds_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.VacationHoldMsg)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.VacationHoldMsg)
  private static final com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg();
  }

  public static com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VacationHoldMsg>
      PARSER = new com.google.protobuf.AbstractParser<VacationHoldMsg>() {
    @java.lang.Override
    public VacationHoldMsg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VacationHoldMsg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VacationHoldMsg> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.VacationHoldMsg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

