// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMessageSpec.proto

// Protobuf Java Version: 3.25.0
package com.resideo.utils.stat.cattgrpccommands;

/**
 * Protobuf type {@code GrpcServices.Verify_ASHRAEMeet_NotMeet}
 */
public final class Verify_ASHRAEMeet_NotMeet extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GrpcServices.Verify_ASHRAEMeet_NotMeet)
    Verify_ASHRAEMeet_NotMeetOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Verify_ASHRAEMeet_NotMeet.newBuilder() to construct.
  private Verify_ASHRAEMeet_NotMeet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Verify_ASHRAEMeet_NotMeet() {
    screenShotPath_ = "";
    iSUItem_ = "";
    iSUValue_ = "";
    isMeetRequirmentMayNotMeet_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Verify_ASHRAEMeet_NotMeet();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Verify_ASHRAEMeet_NotMeet_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Verify_ASHRAEMeet_NotMeet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.class, com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.Builder.class);
  }

  public static final int SCREENSHOTPATH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object screenShotPath_ = "";
  /**
   * <code>string screenShotPath = 1;</code>
   * @return The screenShotPath.
   */
  @java.lang.Override
  public java.lang.String getScreenShotPath() {
    java.lang.Object ref = screenShotPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      screenShotPath_ = s;
      return s;
    }
  }
  /**
   * <code>string screenShotPath = 1;</code>
   * @return The bytes for screenShotPath.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getScreenShotPathBytes() {
    java.lang.Object ref = screenShotPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      screenShotPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUITEM_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object iSUItem_ = "";
  /**
   * <code>string ISUItem = 2;</code>
   * @return The iSUItem.
   */
  @java.lang.Override
  public java.lang.String getISUItem() {
    java.lang.Object ref = iSUItem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iSUItem_ = s;
      return s;
    }
  }
  /**
   * <code>string ISUItem = 2;</code>
   * @return The bytes for iSUItem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getISUItemBytes() {
    java.lang.Object ref = iSUItem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iSUItem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISUVALUE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object iSUValue_ = "";
  /**
   * <code>string ISUValue = 3;</code>
   * @return The iSUValue.
   */
  @java.lang.Override
  public java.lang.String getISUValue() {
    java.lang.Object ref = iSUValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      iSUValue_ = s;
      return s;
    }
  }
  /**
   * <code>string ISUValue = 3;</code>
   * @return The bytes for iSUValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getISUValueBytes() {
    java.lang.Object ref = iSUValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      iSUValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISMEETREQUIRMENT_MAYNOTMEET_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isMeetRequirmentMayNotMeet_ = "";
  /**
   * <code>string isMeetRequirment_MayNotMeet = 4;</code>
   * @return The isMeetRequirmentMayNotMeet.
   */
  @java.lang.Override
  public java.lang.String getIsMeetRequirmentMayNotMeet() {
    java.lang.Object ref = isMeetRequirmentMayNotMeet_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isMeetRequirmentMayNotMeet_ = s;
      return s;
    }
  }
  /**
   * <code>string isMeetRequirment_MayNotMeet = 4;</code>
   * @return The bytes for isMeetRequirmentMayNotMeet.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsMeetRequirmentMayNotMeetBytes() {
    java.lang.Object ref = isMeetRequirmentMayNotMeet_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isMeetRequirmentMayNotMeet_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(screenShotPath_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, screenShotPath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iSUItem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iSUItem_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iSUValue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, iSUValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isMeetRequirmentMayNotMeet_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, isMeetRequirmentMayNotMeet_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(screenShotPath_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, screenShotPath_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iSUItem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iSUItem_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(iSUValue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, iSUValue_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(isMeetRequirmentMayNotMeet_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, isMeetRequirmentMayNotMeet_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet)) {
      return super.equals(obj);
    }
    com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet other = (com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet) obj;

    if (!getScreenShotPath()
        .equals(other.getScreenShotPath())) return false;
    if (!getISUItem()
        .equals(other.getISUItem())) return false;
    if (!getISUValue()
        .equals(other.getISUValue())) return false;
    if (!getIsMeetRequirmentMayNotMeet()
        .equals(other.getIsMeetRequirmentMayNotMeet())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCREENSHOTPATH_FIELD_NUMBER;
    hash = (53 * hash) + getScreenShotPath().hashCode();
    hash = (37 * hash) + ISUITEM_FIELD_NUMBER;
    hash = (53 * hash) + getISUItem().hashCode();
    hash = (37 * hash) + ISUVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getISUValue().hashCode();
    hash = (37 * hash) + ISMEETREQUIRMENT_MAYNOTMEET_FIELD_NUMBER;
    hash = (53 * hash) + getIsMeetRequirmentMayNotMeet().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GrpcServices.Verify_ASHRAEMeet_NotMeet}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GrpcServices.Verify_ASHRAEMeet_NotMeet)
      com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Verify_ASHRAEMeet_NotMeet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Verify_ASHRAEMeet_NotMeet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.class, com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.Builder.class);
    }

    // Construct using com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      screenShotPath_ = "";
      iSUItem_ = "";
      iSUValue_ = "";
      isMeetRequirmentMayNotMeet_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resideo.utils.stat.cattgrpccommands.CattGrpcCommands.internal_static_GrpcServices_Verify_ASHRAEMeet_NotMeet_descriptor;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet getDefaultInstanceForType() {
      return com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.getDefaultInstance();
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet build() {
      com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet buildPartial() {
      com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet result = new com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.screenShotPath_ = screenShotPath_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.iSUItem_ = iSUItem_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.iSUValue_ = iSUValue_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isMeetRequirmentMayNotMeet_ = isMeetRequirmentMayNotMeet_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet) {
        return mergeFrom((com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet other) {
      if (other == com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet.getDefaultInstance()) return this;
      if (!other.getScreenShotPath().isEmpty()) {
        screenShotPath_ = other.screenShotPath_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getISUItem().isEmpty()) {
        iSUItem_ = other.iSUItem_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getISUValue().isEmpty()) {
        iSUValue_ = other.iSUValue_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getIsMeetRequirmentMayNotMeet().isEmpty()) {
        isMeetRequirmentMayNotMeet_ = other.isMeetRequirmentMayNotMeet_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              screenShotPath_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              iSUItem_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              iSUValue_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              isMeetRequirmentMayNotMeet_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object screenShotPath_ = "";
    /**
     * <code>string screenShotPath = 1;</code>
     * @return The screenShotPath.
     */
    public java.lang.String getScreenShotPath() {
      java.lang.Object ref = screenShotPath_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        screenShotPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string screenShotPath = 1;</code>
     * @return The bytes for screenShotPath.
     */
    public com.google.protobuf.ByteString
        getScreenShotPathBytes() {
      java.lang.Object ref = screenShotPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        screenShotPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string screenShotPath = 1;</code>
     * @param value The screenShotPath to set.
     * @return This builder for chaining.
     */
    public Builder setScreenShotPath(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      screenShotPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string screenShotPath = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearScreenShotPath() {
      screenShotPath_ = getDefaultInstance().getScreenShotPath();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string screenShotPath = 1;</code>
     * @param value The bytes for screenShotPath to set.
     * @return This builder for chaining.
     */
    public Builder setScreenShotPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      screenShotPath_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object iSUItem_ = "";
    /**
     * <code>string ISUItem = 2;</code>
     * @return The iSUItem.
     */
    public java.lang.String getISUItem() {
      java.lang.Object ref = iSUItem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iSUItem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ISUItem = 2;</code>
     * @return The bytes for iSUItem.
     */
    public com.google.protobuf.ByteString
        getISUItemBytes() {
      java.lang.Object ref = iSUItem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iSUItem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ISUItem = 2;</code>
     * @param value The iSUItem to set.
     * @return This builder for chaining.
     */
    public Builder setISUItem(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      iSUItem_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string ISUItem = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearISUItem() {
      iSUItem_ = getDefaultInstance().getISUItem();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string ISUItem = 2;</code>
     * @param value The bytes for iSUItem to set.
     * @return This builder for chaining.
     */
    public Builder setISUItemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      iSUItem_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object iSUValue_ = "";
    /**
     * <code>string ISUValue = 3;</code>
     * @return The iSUValue.
     */
    public java.lang.String getISUValue() {
      java.lang.Object ref = iSUValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iSUValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ISUValue = 3;</code>
     * @return The bytes for iSUValue.
     */
    public com.google.protobuf.ByteString
        getISUValueBytes() {
      java.lang.Object ref = iSUValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iSUValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ISUValue = 3;</code>
     * @param value The iSUValue to set.
     * @return This builder for chaining.
     */
    public Builder setISUValue(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      iSUValue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string ISUValue = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearISUValue() {
      iSUValue_ = getDefaultInstance().getISUValue();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string ISUValue = 3;</code>
     * @param value The bytes for iSUValue to set.
     * @return This builder for chaining.
     */
    public Builder setISUValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      iSUValue_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object isMeetRequirmentMayNotMeet_ = "";
    /**
     * <code>string isMeetRequirment_MayNotMeet = 4;</code>
     * @return The isMeetRequirmentMayNotMeet.
     */
    public java.lang.String getIsMeetRequirmentMayNotMeet() {
      java.lang.Object ref = isMeetRequirmentMayNotMeet_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isMeetRequirmentMayNotMeet_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isMeetRequirment_MayNotMeet = 4;</code>
     * @return The bytes for isMeetRequirmentMayNotMeet.
     */
    public com.google.protobuf.ByteString
        getIsMeetRequirmentMayNotMeetBytes() {
      java.lang.Object ref = isMeetRequirmentMayNotMeet_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isMeetRequirmentMayNotMeet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isMeetRequirment_MayNotMeet = 4;</code>
     * @param value The isMeetRequirmentMayNotMeet to set.
     * @return This builder for chaining.
     */
    public Builder setIsMeetRequirmentMayNotMeet(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isMeetRequirmentMayNotMeet_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string isMeetRequirment_MayNotMeet = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsMeetRequirmentMayNotMeet() {
      isMeetRequirmentMayNotMeet_ = getDefaultInstance().getIsMeetRequirmentMayNotMeet();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string isMeetRequirment_MayNotMeet = 4;</code>
     * @param value The bytes for isMeetRequirmentMayNotMeet to set.
     * @return This builder for chaining.
     */
    public Builder setIsMeetRequirmentMayNotMeetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isMeetRequirmentMayNotMeet_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GrpcServices.Verify_ASHRAEMeet_NotMeet)
  }

  // @@protoc_insertion_point(class_scope:GrpcServices.Verify_ASHRAEMeet_NotMeet)
  private static final com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet();
  }

  public static com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Verify_ASHRAEMeet_NotMeet>
      PARSER = new com.google.protobuf.AbstractParser<Verify_ASHRAEMeet_NotMeet>() {
    @java.lang.Override
    public Verify_ASHRAEMeet_NotMeet parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Verify_ASHRAEMeet_NotMeet> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Verify_ASHRAEMeet_NotMeet> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resideo.utils.stat.cattgrpccommands.Verify_ASHRAEMeet_NotMeet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

