@Flycathcer_DIY_With_ISU 
Feature: Flycatcher Registration with ISU 
	Register the FC device by DIY flow 

@FlycatcherDiy_RealDevice_HappyPath_ISU 
Scenario: Test ISU for Fly_thor
#	And Reset stat to "FACTORY DEFAULTS" using CATT
	Then user configures isu "ISU_TSTAT_CONFIGURED" with value "0"	
	Then user configures isu "ISU_LANGUAGE" with value "ISU_100_LANGUAGE__ENGLISH"
	Then user configures isu "ISU_DEVICE_NAME" with value "52"
	Then user configures isu "ISU_TEMP_FORMAT" with value "ISU_125_TEMP_FORMAT__F"
	Then user configures isu "ISU_FLOOR_SENSOR" with value "ISU_565_FLOOR_SENSOR_TYPE__AIR_AND_FLOOR"
	Then user configures isu "ISU_OUTDOOR_TEMPERATURE" with value "ISU_130_ISU_OUTDOOR_TEMPERATURE__NO"	
	Then user configures isu "ISU_HEAT_SYSTEM_TYPE_1" with value "ISU_200_HEAT_SYSTEM_TYPE_1__CONVENTIONAL"
	Then user configures isu "ISU_HEAT_EQUIP_TYPE_1" with value "ISU_205_HEAT_EQUIP_TYPE_1__HIGH_EFFICIENCY_GAS_FORCED_AIR"
	Then user configures isu "ISU_RADIANT_HEAT_STAGES" with value "ISU_208_RADIANT_HEAT_STAGES_0"
	Then user configures isu "ISU_GEOTHM_RFH_STAGE_1_TERMINAL" with value "ISU_315_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_1__1F"
	Then user configures isu "ISU_GEOTHM_RFH_STAGE_2_TERMINAL" with value "ISU_316_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_2__1F"
	Then user configures isu "ISU_GEOTHERMAL_FORCED_AIR_CONTROL" with value "ISU_215_ISU_GEOTHERMAL_FORCED_AIR_CONTROL__HEATING_AND_COOLING"
	Then user configures isu "ISU_REV_VALVE_POLARITY" with value "ISU_218_ISU_REV_VALVE_POLARITY__O"
	Then user configures isu "ISU_COOL_STAGES" with value "1"
	Then user configures isu "ISU_HEAT_STAGES" with value "1"
	Then user configures isu "ISU_HEAT_STAGE_3_TERMINAL" with value "1"
	Then user configures isu "ISU_FAN_OPERATION_IN_HEAT" with value "ISU_230_ISU_FAN_OPERATION_IN_HEAT__EQUIP_CONTROLS_FAN"
	Then user configures isu "ISU_BACKUP_HEAT_TYPE" with value "ISU_235_BACKUP_HEAT_TYPE_NONE"
	Then user configures isu "ISU_BACKUP_HEAT_STAGES" with value "0"
	Then user configures isu "ISU_BACKUP_HEAT_TERMINAL_ASSIGNMENT" with value "1"
	Then user configures isu "ISU_BACKUP_HEAT_OPERATION" with value "ISU_245_ISU_BACKUP_HEAT_OPERATION__NOT_ALLOWED"
	Then user configures isu "ISU_BACKUP_HEAT_FAN_OPERATION" with value "ISU_250_ISU_BACKUP_HEAT_FAN_OPERATION__TSTAT_CONTROLS_FAN"
	Then user configures isu "ISU_AUX_EM_TERMINAL_CONTROL" with value "ISU_253_ISU_AUX_EM_TERMINAL_CONTROL__AUX_AND_E_TOGETHER"
	Then user configures isu "ISU_AUX_BACKUP_TERMINAL_ASSIGNMENT" with value "1"
	Then user configures isu "ISU_AUX_BACKUP_HEAT_TYPE" with value "ISU_255_ISU_AUX_BACKUP_HEAT_TYPE__ELECTRIC_FORCED_AIR"
	Then user configures isu "ISU_EM_HEAT_TYPE" with value "ISU_256_ISU_EM_HEAT_TYPE__ELECTRIC_FORSED_AIR"
	Then user configures isu "ISU_EXTERNAL_FOSSIL_FUEL_KIT" with value "ISU_260_ISU_EXTERNAL_FOSSIL_FUEL_KIT__TSTAT_CONTROLS_BACKUP"
	Then user configures isu "ISU_AUX_BACKUP_HEAT_OPERATION" with value "ISU_265_ISU_AUX_BACKUP_HEAT_OPERATION__NOT_ALLOWED_TO_RUN_WITH_HP"
	Then user configures isu "ISU_EM_HEAT_OPERATION" with value "0"
	Then user configures isu "ISU_AUX_BACKUP_HEAT_FAN_OPERATION" with value "ISU_270_AUX_BACKUP_HEAT_OPERATION__TSTAT_CONTROLS_FAN"	
	Then user configures isu "ISU_EM_HEAT_FAN_OPERATION" with value "ISU_270_AUX_BACKUP_HEAT_OPERATION__TSTAT_CONTROLS_FAN"
	Then user configures isu "ISU_L_TERMINAL" with value "ISU_275_ISU_L_TERMINAL__NONE"
	Then user configures isu "ISU_CONTROL_MODE" with value "2"
	Then user configures isu "ISU_AUTO_CHANGEOVER" with value "ISU_300_ISU_AUTO_CHANGEOVER__AUTOMATIC"
	Then user configures isu "ISU_DEADBAND" with value "0"
	Then user configures isu "ISU_AUTO_DIFFERENTIAL" with value "ISU_303_AUTO_DIFFERENTIAL_0"
	Then user configures isu "ISU_FINISH_WITH_HIGH_COOL_STAGE" with value "ISU_305_FINISH_WITH_HIGH_COOL_STAGE__NO"
	Then user configures isu "ISU_FINISH_WITH_HIGH_HEAT_STAGE" with value "ISU_305_FINISH_WITH_HIGH_HEAT_STAGE__NO"
	Then user configures isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_1" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_1__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_2" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_2__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_3" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_3__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_4" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_4_COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_1" with value "ISU_315_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_1__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_2" with value "ISU_315_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_2__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_HEAT_STAGE_1" with value "ISU_320_DROOP_LOCK_HEAT_STAGE_1__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_HEAT_STAGE_2" with value "ISU_320_DROOP_LOCK_HEAT_STAGE_2__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_HEAT_STAGE_3" with value "ISU_320_DROOP_LOCK_HEAT_STAGE_3__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_1" with value "ISU_325_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_1__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_2" with value "ISU_325_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_2__COMFORT"
	Then user configures isu "ISU_DROOP_SETTING_BACKUP_HEAT" with value "ISU_330_DROOP_SETTING_BACKUP_HEAT__YES"
	Then user configures isu "ISU_DROOP_LOCK_BACKUP_HEAT_STAGE_1" with value "ISU_335_DROOP_LOCK_BACKUP_HEAT_STAGE_1__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_BACKUP_HEAT_STAGE_2" with value "ISU_335_DROOP_LOCK_BACKUP_HEAT_STAGE_2__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_1" with value "ISU_340_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_1__COMFORT"
	Then user configures isu "ISU_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_2" with value "ISU_340_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_2__COMFORT"
	Then user configures isu "ISU_BACKUP_HEAT_UPSTAGE_TIMER" with value "ISU_350_BACKUP_HEAT_UPSTAGE_TIMER__OFF"
	Then user configures isu "ISU_HP_CMPR_LOCKOUT" with value "ISU_355_HP_CMPR_LOCKOUT_OFF"
	Then user configures isu "ISU_HP_AUX_LOCKOUT" with value "ISU_356_HP_AUX_LOCKOUT_OFF"
	Then user configures isu "ISU_CPH_RADIANTS_1" with value "3"
	Then user configures isu "ISU_CPH_RADIANTS_2" with value "3"
	Then user configures isu "ISU_CPH_COOLS1" with value "3"
	Then user configures isu "ISU_CPH_COOLS2" with value "3"
	Then user configures isu "ISU_CPH_COOLS3" with value "3"
	Then user configures isu "ISU_CPH_COOLS4" with value "3"
	Then user configures isu "ISU_CPH_HEATS1" with value "3"
	Then user configures isu "ISU_CPH_HEATS2" with value "3"
	Then user configures isu "ISU_CPH_HEATS3" with value "3"	
	Then user configures isu "ISU_CPH_BACKUP1" with value "9"
	Then user configures isu "ISU_CPH_BACKUP2" with value "9"
	Then user configures isu "ISU_CPH_EM1" with value "9"
	Then user configures isu "ISU_PID_COOLING_THROTTLING_RANGE" with value "2"
	Then user configures isu "ISU_PID_COOLING_INTEGRAL" with value "100"
	Then user configures isu "ISU_PID_COOLING_DERIVATIVE" with value "0"
	Then user configures isu "ISU_PID_HEATING_THROTTLING_RANGE" with value "2"
	Then user configures isu "ISU_PID_HEATING_INTEGRAL" with value "100"
	Then user configures isu "ISU_PID_HEATING_DERIVATIVE" with value "0"	
	Then user configures isu "ISU_MIN_NONCMPR_OFF" with value "ISU_386_MIN_NONCMPR_OFF__OFF"	
	Then user configures isu "ISU_MIN_CMPR_OFF" with value "ISU_387_MIN_CMPR_OFF__5MIN"
	Then user configures isu "ISU_MIN_NONCMPR_ON" with value "0"
	Then user configures isu "ISU_MIN_CMPR_ON" with value "0"	
	Then user configures isu "ISU_COOL_FAN_OVRN" with value "0"
	Then user configures isu "ISU_HEAT_FAN_OVRN" with value "0"
	Then user configures isu "ISU_LOW_LOAD_CONTROL" with value "0"	
	Then user configures isu "ISU_MIN_HEAT_RECOVERY_RAMP_RATE" with value "5"
	Then user configures isu "ISU_MIN_HEAT_OUTDOOR_TEMP" with value "20"
	Then user configures isu "ISU_MAX_HEAT_RECOVERY_RAMP_RATE" with value "8"
	Then user configures isu "ISU_MAX_HEAT_RECOVERY_RAMP_RATE" with value "60"
	Then user configures isu "ISU_MAX_HEAT_OUTDOOR_TEMP" with value "60"
	Then user configures isu "ISU_MIN_COOL_RECOVERY_RAMP_RATE" with value "3"
	Then user configures isu "ISU_MIN_COOL_OUTDOOR_TEMP" with value "110"
	Then user configures isu "ISU_MAX_COOL_RECOVERY_RAMP_RATE" with value "6"
	Then user configures isu "ISU_MAX_COOL_OUTDOOR_TEMP" with value "90"
	Then user configures isu "ISU_AIR_ENABLE" with value "ISU_425_AIR_ENABLE__YES"
	Then user configures isu "ISU_OPTIMAL_STOP" with value "0"
	Then user configures isu "ISU_MIN_COOL_SP" with value "50"
	Then user configures isu "ISU_MAX_COOL_SP" with value "90"
	Then user configures isu "ISU_MIN_HEAT_SP" with value "50"
	Then user configures isu "ISU_MAX_HEAT_SP" with value "90"
	Then user configures isu "ISU_PUMP_EXERCISE_ENABLE" with value "0"
	Then user configures isu "ISU_MAXIMUM_CENTRAL_HEATING_SETPOINT" with value "194"
	Then user configures isu "ISU_KEYPAD_LOCKOUT" with value "ISU_435_KEYPAD_LOCKOUT__NONE"
	Then user configures isu "ISU_STAT_CONFIG_SENSORS" with value "0"
	Then user configures isu "ISU_INDOOR_TEMP_SENSOR" with value "ISU_500_INDOOR_TEMP_SENSOR__NO"
	Then user configures isu "ISU_OUTDOOR_TEMP_SENSOR" with value "ISU_500_OUTDOOR_TEMP_SENSOR__NO"
	Then user configures isu "ISU_FLOOR_TEMP_SENSOR" with value "ISU_500_FLOOR_TEMP_SENSOR__NO"
	Then user configures isu "ISU_INDOOR_SENSOR_NAME" with value "0"
	Then user configures isu "ISU_INDOOR_TEMP_SENSOR_WIRING_ASSIGNMENT" with value "ISU_510_INDOOR_TEMP_SENSOR_WIRING_ASSIGNMENT__TERMINAL_NOT_CONFIGURED"
	Then user configures isu "ISU_INDOOR_SENSOR_TYPE" with value "ISU_515_INDOOR_SENSOR_TYPE__SENSOR_TEMPERATURE_10K"
	Then user configures isu "ISU_TEMP_SENSOR_SELECTION" with value "ISU_520_TEMP_SENSOR_SELECTION__AVERAGE"
	Then user configures isu "ISU_OUTDOOR_TEMP_SENSOR_WIRING_ASSIGNMENT" with value "1"
	Then user configures isu "ISU_FLOOR_SENSOR_WIRING_ASSIGNMENT" with value "ISU_560_FLOOR_SENSOR_WIRING_ASSIGNMENT__TERMINAL_NOT_CONFIGURED"
	Then user configures isu "ISU_FLOOR_ECONOMY_MODE" with value "0"
	Then user configures isu "ISU_FLOOR_SETPOINT" with value "70"
	Then user configures isu "ISU_FILTER_TYPE" with value "2"
	Then user configures isu "ISU_NUM_AIR_FILTERS" with value "1"
	Then user configures isu "ISU_FILTER1_TIMER" with value "ISU_711_FILTER1_TIMER__OFF"
	Then user configures isu "ISU_FILTER2_TIMER" with value "ISU_712_FILTER2_TIMER__OFF"
	Then user configures isu "ISU_EAC_CLEANING_TIMER" with value "0"
	Then user configures isu "ISU_EAC_PRE_FILTER_TIMER" with value "0"
	Then user configures isu "ISU_EAC_POST_FILTER_TIMER" with value "0"
	Then user configures isu "ISU_HUMIDIFIER_TYPE" with value "ISU_8000_HUM_TYPE_NONE"
	Then user configures isu "ISU_INDOOR_HUM_SENSOR" with value "ISU_8010_HUM_SENSOR_WIRELESS1"
	Then user configures isu "ISU_HUMIDIFIER1_WIRING_ASSIGNMENT" with value "3"
	Then user configures isu "ISU_HUM_FROST_PROTECTION" with value "ISU_8050_HUM_FROST_PROTECTION_OFF"
	Then user configures isu "ISU_HUM_SYSTEM_MODE" with value "ISU_8060_HUM_MODE_HEAT"
	Then user configures isu "ISU_HUM_FAN_CONTROL" with value "ISU_8070_HUM_ONLY_WITH_FAN"
	Then user configures isu "ISU_HUM_COOL_CALL_LOCKOUT" with value "ISU_8080_ALLOW_HUM_IN_COOL"
	Then user configures isu "ISU_HUM_TANK_FILTER_TIMER" with value "HUM_TANK_TIMER_DISABLED"
	Then user configures isu "ISU_HUMPAD_TIMER" with value "ISU_810_HUMPAD_TIMER__HUM_TANK_TIMER_DISABLED"
	Then user configures isu "ISU_DEHUM_EQUIP" with value "ISU_9000_DEHUM_EQUIPMENT__NONE"
	Then user configures isu "ISU_INDOOR_DEHUM_SENSOR" with value "ISU_9010_DEHUM_SENSOR_THERMOSTAT"
	Then user configures isu "ISU_HUM_SENSOR_DISPLAY" with value "ISU_9020_HUM_DISPLAY_SENS_HUM"
	Then user configures isu "ISU_DEHUMIDIFIER_WIRING_ASSIGNMENT" with value "ISU_9040_TERMINAL_NOT_CONFIGURED"
	Then user configures isu "ISU_DEHUM_RELAY" with value "ISU_9050__DEHUM_RELAY_NORMALLY_OPEN"
	Then user configures isu "ISU_DEHUM_ALGORITHM" with value "ISU_9060__DEHUM_ALG_ITHC_DROOP"
	Then user configures isu "ISU_DEHUM_MAX_DROOP" with value "ISU_9070__DEHUM_MAX_DROOP_3"
	Then user configures isu "ISU_COMMERCIAL_DEHUM_VIA_COOLING" with value "ISU_9080__DEHUM_VIA_COOLING_NONE"
	Then user configures isu "ISU_DEHUM_MINUTES_ON" with value "ISU_9090__DEHUM_MINUTES_10_MINUTES"
	Then user configures isu "ISU_DEHUM_SYSTEM_MODE" with value "6"
	Then user configures isu "ISU_DEHUM_FAN_MODE" with value "ISU_9130__STAT_CTRLS_FAN"
	Then user configures isu "ISU_WHOLE_HOUSE_DEHUM_LOCK" with value "ISU_9140__ALLOW_DEHUM_IN_COOL"
	Then user configures isu "ISU_SOUTHERN_DEHUM_MODE" with value "ISU_9180_SOUTHERN_DEHUM_DISABLED"
	Then user configures isu "ISU_SOUTHERN_DEHUM_FAN" with value "0"
	Then user configures isu "ISU_SOUTHERN_DEHUM_LOW_LIMIT" with value "76"
	Then user configures isu "ISU_SOUTHERN_DEHUM_TEMP_SETPOINT" with value "85"
	Then user configures isu "ISU_SOUTHERN_DEHUM_RH_SETPOINT" with value "65"
	Then user configures isu "ISU_DEHUM_FILTER_TIMER" with value "ISU_921_DEHUM_FILTER_TIMER__DEHUM_FILTER_TIMER_DISABLED"
	Then user configures isu "ISU_VENT_TYPE" with value "ISU_1000_VENT_TYPE_NONE"
	Then user configures isu "ISU_VENT_WIRING_ASSIGNMENT" with value "ISU_1002_VENT_WIRING_ASSIGNMENT_NONE"
	Then user configures isu "ISU_VENT_ALGORITHM" with value "ISU_1005_VENT_ALGORITHM_ASHRAE"
	Then user configures isu "ISU_VENT_CTRL_FAN_MODE" with value "ISU_1006_VENT_CTRL_FAN_MODE__TSTAT_CTRLS_FAN"
	Then user configures isu "ISU_VENT_CTRL_BEDROOMS" with value "ISU_1007_VENT_CTRL_BEDROOMS_2"
	Then user configures isu "ISU_VENT_CTRL_SQ_FT" with value "ISU_1008_VENT_CTRL_SQ_FT__1000"
	Then user configures isu "ISU_VENT_HIGH_SPEED_CFM" with value "ISU_1009_VENT_HIGH_SPEED_CFM__30"
	Then user configures isu "ISU_VENT_NUM_AIR_CHANGES" with value "7"
	Then user configures isu "ISU_VENT_PERCENT_ON_TIME" with value "ISU_1011_VENT_PERCENT_ON_TIME_30"
	Then user configures isu "ISU_VENT_PRIORITY" with value "ISU_1012_VENT_PRIORITY_LOCKOUTS"
	Then user configures isu "ISU_VENT_LOCKOUT_TEMP_LOW" with value "ISU_1013_VENT_LOCKOUT_TEMP_LOW_OFF"
	Then user configures isu "ISU_VENT_LOCKOUT_TEMP_HIGH" with value "ISU_1014_VENT_LOCKOUT_TEMP_HIGH_OFF"
	Then user configures isu "ISU_VENT_LOCKOUT_DEWPOINT_HIGH_VALUE" with value "ISU_1015_VENT_LOCKOUT_DEWPOINT_HIGH_VALUE_OFF"
	Then user configures isu "ISU_VENT_LOCKOUT_HUM_DEHUM_CALL" with value "0"
	Then user configures isu "ISU_VENT_CTRL" with value "ISU_1016_VENT_CTRL_ENABLED_ALL_PERIODS"
	Then user configures isu "ISU_DEHUM_VIA_VENT" with value "0"
	Then user configures isu "ISU_VENT_CORE_CLEANING_TIMER" with value "ISU_1017_VENT_CORE_CLEANING_TIMER_DISABLED"
	Then user configures isu "ISU_VENT_FILTER_TIMER" with value "ISU_1018_VENT_FILTER_TIMER_DISABLED"
	Then user configures isu "ISU_UV_NUM_BULBS" with value "0"
	Then user configures isu "ISU_UVLAMP1_TIMER" with value "ISU_1105_UVLAMP1_TIMER_UV_DISABLED"
	Then user configures isu "ISU_UVLAMP2_TIMER" with value "ISU_1106_UVLAMP2_TIMER_UV_DISABLED"
	Then user configures isu "ISU_INSTALLER_CUSTOM_REMINDERS" with value "1"
	Then user configures isu "ISU_ACTIVE_BACKLIGHT" with value "4"
	Then user configures isu "ISU_BACKLIGHT" with value "ISU_1400_BACKLIGHT_CONTINUOUS"
	Then user configures isu "ISU_INACTIVE_BACKLIGHT" with value "5"
	Then user configures isu "ISU_NIGHT_TIME_INACTIVE_BACKLIGHT" with value "2"
	Then user configures isu "ISU_ACTIVE_BACKLIGHT_START_TIME" with value "28"
	Then user configures isu "ISU_NIGHT_TIME_BACKLIGHT_START_TIME" with value "84"
	Then user configures isu "ISU_CLOCK_FORMAT" with value "ISU_1410_CLOCK_FORMAT_12HR"
	Then user configures isu "ISU_DST_TYPE" with value "ISU_1415_DST_TYPE__ON"
	Then user configures isu "ISU_TEMP_OFFSET" with value "ISU_1420_TEMP_OFFSET__0"
	Then user configures isu "ISU_HUMID_OFFSET" with value "12"
	Then user configures isu "ISU_HOT_WATER_CONTROL_FUNCTION" with value "0"
	Then user configures isu "ISU_HOT_WATER_SETPOINT" with value "50"
	Then user configures isu "ISU_DISINFECTION_CYCLE" with value "1"
	Then user configures isu "ISU_OPENTHERM_MAX_SUPPLY_WATER_TEMPERATURE" with value "60"
	Then user configures isu "ISU_OTC_CONTROL" with value "0"
	Then user configures isu "ISU_OTC_CURVE" with value "16"
	Then user configures isu "ISU_OPENTHERM_ROOM_COMPENSATION" with value "0"
	Then user configures isu "ISU_FAIL_SAVE_MODE" with value "0"
	Then user configures isu "ISU_DEALER_NAME" with value "0"
	Then user configures isu "ISU_DEALER_PHONE" with value "0"
	Then user configures isu "ISU_DEALER_EMAIL_ADDRESS" with value "0"
	Then user configures isu "ISU_DEALER_WEBSITE" with value "0"
	Then user configures isu "ISU_DEALER_MESSAGE" with value "0"
	
	
	
	
#	Then user verifies isu "ISU_TSTAT_CONFIGURED" with value "0"	
#	Then user verifies isu "ISU_LANGUAGE" with value "ISU_100_LANGUAGE__ENGLISH"
#	Then user verifies isu "ISU_DEVICE_NAME" with value "52"
#	Then user verifies isu "ISU_TEMP_FORMAT" with value "ISU_125_TEMP_FORMAT__F"
#	Then user verifies isu "ISU_FLOOR_SENSOR" with value "ISU_565_FLOOR_SENSOR_TYPE__AIR_AND_FLOOR"
#	Then user verifies isu "ISU_OUTDOOR_TEMPERATURE" with value "ISU_130_ISU_OUTDOOR_TEMPERATURE__NO"	
#	Then user verifies isu "ISU_HEAT_SYSTEM_TYPE_1" with value "ISU_200_HEAT_SYSTEM_TYPE_1__CONVENTIONAL"
#	Then user verifies isu "ISU_HEAT_EQUIP_TYPE_1" with value "ISU_205_HEAT_EQUIP_TYPE_1__HIGH_EFFICIENCY_GAS_FORCED_AIR"
#	Then user verifies isu "ISU_RADIANT_HEAT_STAGES" with value "ISU_208_RADIANT_HEAT_STAGES_0"
#	Then user verifies isu "ISU_GEOTHM_RFH_STAGE_1_TERMINAL" with value "ISU_315_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_1__1F"
#	Then user verifies isu "ISU_GEOTHM_RFH_STAGE_2_TERMINAL" with value "ISU_316_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_2__1F"
#	Then user verifies isu "ISU_GEOTHERMAL_FORCED_AIR_CONTROL" with value "ISU_215_ISU_GEOTHERMAL_FORCED_AIR_CONTROL__HEATING_AND_COOLING"
#	Then user verifies isu "ISU_REV_VALVE_POLARITY" with value "ISU_218_ISU_REV_VALVE_POLARITY__O"
#	Then user verifies isu "ISU_COOL_STAGES" with value "1"
#	Then user verifies isu "ISU_HEAT_STAGES" with value "1"
#	Then user verifies isu "ISU_HEAT_STAGE_3_TERMINAL" with value "1"
#	Then user verifies isu "ISU_FAN_OPERATION_IN_HEAT" with value "ISU_230_ISU_FAN_OPERATION_IN_HEAT__EQUIP_CONTROLS_FAN"
#	Then user verifies isu "ISU_BACKUP_HEAT_TYPE" with value "ISU_235_BACKUP_HEAT_TYPE_NONE"
#	Then user verifies isu "ISU_BACKUP_HEAT_STAGES" with value "0"
#	Then user verifies isu "ISU_BACKUP_HEAT_TERMINAL_ASSIGNMENT" with value "1"
#	Then user verifies isu "ISU_BACKUP_HEAT_OPERATION" with value "ISU_245_ISU_BACKUP_HEAT_OPERATION__NOT_ALLOWED"
#	Then user verifies isu "ISU_BACKUP_HEAT_FAN_OPERATION" with value "ISU_250_ISU_BACKUP_HEAT_FAN_OPERATION__TSTAT_CONTROLS_FAN"
#	Then user verifies isu "ISU_AUX_EM_TERMINAL_CONTROL" with value "ISU_253_ISU_AUX_EM_TERMINAL_CONTROL__AUX_AND_E_TOGETHER"
#	Then user verifies isu "ISU_AUX_BACKUP_TERMINAL_ASSIGNMENT" with value "1"
#	Then user verifies isu "ISU_AUX_BACKUP_HEAT_TYPE" with value "ISU_255_ISU_AUX_BACKUP_HEAT_TYPE__ELECTRIC_FORCED_AIR"
#	Then user verifies isu "ISU_EM_HEAT_TYPE" with value "ISU_256_ISU_EM_HEAT_TYPE__ELECTRIC_FORSED_AIR"
#	Then user verifies isu "ISU_EXTERNAL_FOSSIL_FUEL_KIT" with value "ISU_260_ISU_EXTERNAL_FOSSIL_FUEL_KIT__TSTAT_CONTROLS_BACKUP"
#	Then user verifies isu "ISU_AUX_BACKUP_HEAT_OPERATION" with value "ISU_265_ISU_AUX_BACKUP_HEAT_OPERATION__NOT_ALLOWED_TO_RUN_WITH_HP"
#	Then user verifies isu "ISU_EM_HEAT_OPERATION" with value "0"
#	Then user verifies isu "ISU_AUX_BACKUP_HEAT_FAN_OPERATION" with value "ISU_270_AUX_BACKUP_HEAT_OPERATION__TSTAT_CONTROLS_FAN"	
#	Then user verifies isu "ISU_EM_HEAT_FAN_OPERATION" with value "ISU_270_AUX_BACKUP_HEAT_OPERATION__TSTAT_CONTROLS_FAN"
#	Then user verifies isu "ISU_L_TERMINAL" with value "ISU_275_ISU_L_TERMINAL__NONE"
#	Then user verifies isu "ISU_CONTROL_MODE" with value "2"
#	Then user verifies isu "ISU_AUTO_CHANGEOVER" with value "ISU_300_ISU_AUTO_CHANGEOVER__AUTOMATIC"
#	Then user verifies isu "ISU_DEADBAND" with value "0"
#	Then user verifies isu "ISU_AUTO_DIFFERENTIAL" with value "ISU_303_AUTO_DIFFERENTIAL_0"
#	Then user verifies isu "ISU_FINISH_WITH_HIGH_COOL_STAGE" with value "ISU_305_FINISH_WITH_HIGH_COOL_STAGE__NO"
#	Then user verifies isu "ISU_FINISH_WITH_HIGH_HEAT_STAGE" with value "ISU_305_FINISH_WITH_HIGH_HEAT_STAGE__NO"
#	Then user verifies isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_1" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_1__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_2" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_2__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_3" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_3__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_4" with value "ISU_310_DROOP_LOCK_COOLING_COMPRESSOR_STAGE_4_COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_1" with value "ISU_315_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_1__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_2" with value "ISU_315_DROOP_LOCK_GEOTHERMAL_RFH_STAGE_2__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_HEAT_STAGE_1" with value "ISU_320_DROOP_LOCK_HEAT_STAGE_1__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_HEAT_STAGE_2" with value "ISU_320_DROOP_LOCK_HEAT_STAGE_2__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_HEAT_STAGE_3" with value "ISU_320_DROOP_LOCK_HEAT_STAGE_3__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_1" with value "ISU_325_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_1__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_2" with value "ISU_325_DROOP_LOCK_HEAT_COMPRESSOR_STAGE_2__COMFORT"
#	Then user verifies isu "ISU_DROOP_SETTING_BACKUP_HEAT" with value "ISU_330_DROOP_SETTING_BACKUP_HEAT__YES"
#	Then user verifies isu "ISU_DROOP_LOCK_BACKUP_HEAT_STAGE_1" with value "ISU_335_DROOP_LOCK_BACKUP_HEAT_STAGE_1__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_BACKUP_HEAT_STAGE_2" with value "ISU_335_DROOP_LOCK_BACKUP_HEAT_STAGE_2__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_1" with value "ISU_340_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_1__COMFORT"
#	Then user verifies isu "ISU_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_2" with value "ISU_340_DROOP_LOCK_AUX_BACKUP_HEAT_STAGE_2__COMFORT"
#	Then user verifies isu "ISU_BACKUP_HEAT_UPSTAGE_TIMER" with value "ISU_350_BACKUP_HEAT_UPSTAGE_TIMER__OFF"
#	Then user verifies isu "ISU_HP_CMPR_LOCKOUT" with value "ISU_355_HP_CMPR_LOCKOUT_OFF"
#	Then user verifies isu "ISU_HP_AUX_LOCKOUT" with value "ISU_356_HP_AUX_LOCKOUT_OFF"
#	Then user verifies isu "ISU_CPH_RADIANTS_1" with value "3"
#	Then user verifies isu "ISU_CPH_RADIANTS_2" with value "3"
#	Then user verifies isu "ISU_CPH_COOLS1" with value "3"
#	Then user verifies isu "ISU_CPH_COOLS2" with value "3"
#	Then user verifies isu "ISU_CPH_COOLS3" with value "3"
#	Then user verifies isu "ISU_CPH_COOLS4" with value "3"
#	Then user verifies isu "ISU_CPH_HEATS1" with value "3"
#	Then user verifies isu "ISU_CPH_HEATS2" with value "3"
#	Then user verifies isu "ISU_CPH_HEATS3" with value "3"	
#	Then user verifies isu "ISU_CPH_BACKUP1" with value "9"
#	Then user verifies isu "ISU_CPH_BACKUP2" with value "9"
#	Then user verifies isu "ISU_CPH_EM1" with value "9"
#	Then user verifies isu "ISU_PID_COOLING_THROTTLING_RANGE" with value "2"
#	Then user verifies isu "ISU_PID_COOLING_INTEGRAL" with value "100"
#	Then user verifies isu "ISU_PID_COOLING_DERIVATIVE" with value "0"
#	Then user verifies isu "ISU_PID_HEATING_THROTTLING_RANGE" with value "2"
#	Then user verifies isu "ISU_PID_HEATING_INTEGRAL" with value "100"
#	Then user verifies isu "ISU_PID_HEATING_DERIVATIVE" with value "0"	
#	Then user verifies isu "ISU_MIN_NONCMPR_OFF" with value "ISU_386_MIN_NONCMPR_OFF__OFF"	
#	Then user verifies isu "ISU_MIN_CMPR_OFF" with value "ISU_387_MIN_CMPR_OFF__5MIN"
#	Then user verifies isu "ISU_MIN_NONCMPR_ON" with value "0"
#	Then user verifies isu "ISU_MIN_CMPR_ON" with value "0"	
#	Then user verifies isu "ISU_COOL_FAN_OVRN" with value "0"
#	Then user verifies isu "ISU_HEAT_FAN_OVRN" with value "0"
#	Then user verifies isu "ISU_LOW_LOAD_CONTROL" with value "0"	
#	Then user verifies isu "ISU_MIN_HEAT_RECOVERY_RAMP_RATE" with value "5"
#	Then user verifies isu "ISU_MIN_HEAT_OUTDOOR_TEMP" with value "20"
#	Then user verifies isu "ISU_MAX_HEAT_RECOVERY_RAMP_RATE" with value "8"
#	Then user verifies isu "ISU_MAX_HEAT_RECOVERY_RAMP_RATE" with value "60"
#	Then user verifies isu "ISU_MAX_HEAT_OUTDOOR_TEMP" with value "60"
#	Then user verifies isu "ISU_MIN_COOL_RECOVERY_RAMP_RATE" with value "3"
#	Then user verifies isu "ISU_MIN_COOL_OUTDOOR_TEMP" with value "110"
#	Then user verifies isu "ISU_MAX_COOL_RECOVERY_RAMP_RATE" with value "6"
#	Then user verifies isu "ISU_MAX_COOL_OUTDOOR_TEMP" with value "90"
#	Then user verifies isu "ISU_AIR_ENABLE" with value "ISU_425_AIR_ENABLE__YES"
#	Then user verifies isu "ISU_OPTIMAL_STOP" with value "0"
#	Then user verifies isu "ISU_MIN_COOL_SP" with value "50"
#	Then user verifies isu "ISU_MAX_COOL_SP" with value "90"
#	Then user verifies isu "ISU_MIN_HEAT_SP" with value "50"
#	Then user verifies isu "ISU_MAX_HEAT_SP" with value "90"
#	Then user verifies isu "ISU_PUMP_EXERCISE_ENABLE" with value "0"
#	Then user verifies isu "ISU_MAXIMUM_CENTRAL_HEATING_SETPOINT" with value "194"
#	Then user verifies isu "ISU_KEYPAD_LOCKOUT" with value "ISU_435_KEYPAD_LOCKOUT__NONE"
#	Then user verifies isu "ISU_STAT_CONFIG_SENSORS" with value "0"
#	Then user verifies isu "ISU_INDOOR_TEMP_SENSOR" with value "ISU_500_INDOOR_TEMP_SENSOR__NO"
#	Then user verifies isu "ISU_OUTDOOR_TEMP_SENSOR" with value "ISU_500_OUTDOOR_TEMP_SENSOR__NO"
#	Then user verifies isu "ISU_FLOOR_TEMP_SENSOR" with value "ISU_500_FLOOR_TEMP_SENSOR__NO"
#	Then user verifies isu "ISU_INDOOR_SENSOR_NAME" with value "0"
#	Then user verifies isu "ISU_INDOOR_TEMP_SENSOR_WIRING_ASSIGNMENT" with value "ISU_510_INDOOR_TEMP_SENSOR_WIRING_ASSIGNMENT__TERMINAL_NOT_CONFIGURED"
#	Then user verifies isu "ISU_INDOOR_SENSOR_TYPE" with value "ISU_515_INDOOR_SENSOR_TYPE__SENSOR_TEMPERATURE_10K"
#	Then user verifies isu "ISU_TEMP_SENSOR_SELECTION" with value "ISU_520_TEMP_SENSOR_SELECTION__AVERAGE"
#	Then user verifies isu "ISU_OUTDOOR_TEMP_SENSOR_WIRING_ASSIGNMENT" with value "1"
#	Then user verifies isu "ISU_FLOOR_SENSOR_WIRING_ASSIGNMENT" with value "ISU_560_FLOOR_SENSOR_WIRING_ASSIGNMENT__TERMINAL_NOT_CONFIGURED"
#	Then user verifies isu "ISU_FLOOR_ECONOMY_MODE" with value "0"
#	Then user verifies isu "ISU_FLOOR_SETPOINT" with value "70"
#	Then user verifies isu "ISU_FILTER_TYPE" with value "2"
#	Then user verifies isu "ISU_NUM_AIR_FILTERS" with value "1"
#	Then user verifies isu "ISU_FILTER1_TIMER" with value "ISU_711_FILTER1_TIMER__OFF"
#	Then user verifies isu "ISU_FILTER2_TIMER" with value "ISU_712_FILTER2_TIMER__OFF"
#	Then user verifies isu "ISU_EAC_CLEANING_TIMER" with value "0"
#	Then user verifies isu "ISU_EAC_PRE_FILTER_TIMER" with value "0"
#	Then user verifies isu "ISU_EAC_POST_FILTER_TIMER" with value "0"
#	Then user verifies isu "ISU_HUMIDIFIER_TYPE" with value "ISU_8000_HUM_TYPE_NONE"
#	Then user verifies isu "ISU_INDOOR_HUM_SENSOR" with value "ISU_8010_HUM_SENSOR_WIRELESS1"
#	Then user verifies isu "ISU_HUMIDIFIER1_WIRING_ASSIGNMENT" with value "3"
#	Then user verifies isu "ISU_HUM_FROST_PROTECTION" with value "ISU_8050_HUM_FROST_PROTECTION_OFF"
#	Then user verifies isu "ISU_HUM_SYSTEM_MODE" with value "ISU_8060_HUM_MODE_HEAT"
#	Then user verifies isu "ISU_HUM_FAN_CONTROL" with value "ISU_8070_HUM_ONLY_WITH_FAN"
#	Then user verifies isu "ISU_HUM_COOL_CALL_LOCKOUT" with value "ISU_8080_ALLOW_HUM_IN_COOL"
#	Then user verifies isu "ISU_HUM_TANK_FILTER_TIMER" with value "HUM_TANK_TIMER_DISABLED"
#	Then user verifies isu "ISU_HUMPAD_TIMER" with value "ISU_810_HUMPAD_TIMER__HUM_TANK_TIMER_DISABLED"
#	Then user verifies isu "ISU_DEHUM_EQUIP" with value "ISU_9000_DEHUM_EQUIPMENT__NONE"
#	Then user verifies isu "ISU_INDOOR_DEHUM_SENSOR" with value "ISU_9010_DEHUM_SENSOR_THERMOSTAT"
#	Then user verifies isu "ISU_HUM_SENSOR_DISPLAY" with value "ISU_9020_HUM_DISPLAY_SENS_HUM"
#	Then user verifies isu "ISU_DEHUMIDIFIER_WIRING_ASSIGNMENT" with value "ISU_9040_TERMINAL_NOT_CONFIGURED"
#	Then user verifies isu "ISU_DEHUM_RELAY" with value "ISU_9050__DEHUM_RELAY_NORMALLY_OPEN"
#	Then user verifies isu "ISU_DEHUM_ALGORITHM" with value "ISU_9060__DEHUM_ALG_ITHC_DROOP"
#	Then user verifies isu "ISU_DEHUM_MAX_DROOP" with value "ISU_9070__DEHUM_MAX_DROOP_3"
#	Then user verifies isu "ISU_COMMERCIAL_DEHUM_VIA_COOLING" with value "ISU_9080__DEHUM_VIA_COOLING_NONE"
#	Then user verifies isu "ISU_DEHUM_MINUTES_ON" with value "ISU_9090__DEHUM_MINUTES_10_MINUTES"
#	Then user verifies isu "ISU_DEHUM_SYSTEM_MODE" with value "6"
#	Then user verifies isu "ISU_DEHUM_FAN_MODE" with value "ISU_9130__STAT_CTRLS_FAN"
#	Then user verifies isu "ISU_WHOLE_HOUSE_DEHUM_LOCK" with value "ISU_9140__ALLOW_DEHUM_IN_COOL"
#	Then user verifies isu "ISU_SOUTHERN_DEHUM_MODE" with value "ISU_9180_SOUTHERN_DEHUM_DISABLED"
#	Then user verifies isu "ISU_SOUTHERN_DEHUM_FAN" with value "0"
#	Then user verifies isu "ISU_SOUTHERN_DEHUM_LOW_LIMIT" with value "76"
#	Then user verifies isu "ISU_SOUTHERN_DEHUM_TEMP_SETPOINT" with value "85"
#	Then user verifies isu "ISU_SOUTHERN_DEHUM_RH_SETPOINT" with value "65"
#	Then user verifies isu "ISU_DEHUM_FILTER_TIMER" with value "ISU_921_DEHUM_FILTER_TIMER__DEHUM_FILTER_TIMER_DISABLED"
#	Then user verifies isu "ISU_VENT_TYPE" with value "ISU_1000_VENT_TYPE_NONE"
#	Then user verifies isu "ISU_VENT_WIRING_ASSIGNMENT" with value "ISU_1002_VENT_WIRING_ASSIGNMENT_NONE"
#	Then user verifies isu "ISU_VENT_ALGORITHM" with value "ISU_1005_VENT_ALGORITHM_ASHRAE"
#	Then user verifies isu "ISU_VENT_CTRL_FAN_MODE" with value "ISU_1006_VENT_CTRL_FAN_MODE__TSTAT_CTRLS_FAN"
#	Then user verifies isu "ISU_VENT_CTRL_BEDROOMS" with value "ISU_1007_VENT_CTRL_BEDROOMS_2"
#	Then user verifies isu "ISU_VENT_CTRL_SQ_FT" with value "ISU_1008_VENT_CTRL_SQ_FT__1000"
#	Then user verifies isu "ISU_VENT_HIGH_SPEED_CFM" with value "ISU_1009_VENT_HIGH_SPEED_CFM__30"
#	Then user verifies isu "ISU_VENT_NUM_AIR_CHANGES" with value "7"
#	Then user verifies isu "ISU_VENT_PERCENT_ON_TIME" with value "ISU_1011_VENT_PERCENT_ON_TIME_30"
#	Then user verifies isu "ISU_VENT_PRIORITY" with value "ISU_1012_VENT_PRIORITY_LOCKOUTS"
#	Then user verifies isu "ISU_VENT_LOCKOUT_TEMP_LOW" with value "ISU_1013_VENT_LOCKOUT_TEMP_LOW_OFF"
#	Then user verifies isu "ISU_VENT_LOCKOUT_TEMP_HIGH" with value "ISU_1014_VENT_LOCKOUT_TEMP_HIGH_OFF"
#	Then user verifies isu "ISU_VENT_LOCKOUT_DEWPOINT_HIGH_VALUE" with value "ISU_1015_VENT_LOCKOUT_DEWPOINT_HIGH_VALUE_OFF"
#	Then user verifies isu "ISU_VENT_LOCKOUT_HUM_DEHUM_CALL" with value "0"
#	Then user verifies isu "ISU_VENT_CTRL" with value "ISU_1016_VENT_CTRL_ENABLED_ALL_PERIODS"
#	Then user verifies isu "ISU_DEHUM_VIA_VENT" with value "0"
#	Then user verifies isu "ISU_VENT_CORE_CLEANING_TIMER" with value "ISU_1017_VENT_CORE_CLEANING_TIMER_DISABLED"
#	Then user verifies isu "ISU_VENT_FILTER_TIMER" with value "ISU_1018_VENT_FILTER_TIMER_DISABLED"
#	Then user verifies isu "ISU_UV_NUM_BULBS" with value "0"
#	Then user verifies isu "ISU_UVLAMP1_TIMER" with value "ISU_1105_UVLAMP1_TIMER_UV_DISABLED"
#	Then user verifies isu "ISU_UVLAMP2_TIMER" with value "ISU_1106_UVLAMP2_TIMER_UV_DISABLED"
#	Then user verifies isu "ISU_INSTALLER_CUSTOM_REMINDERS" with value "1"
#	Then user verifies isu "ISU_ACTIVE_BACKLIGHT" with value "4"
#	Then user verifies isu "ISU_BACKLIGHT" with value "ISU_1400_BACKLIGHT_CONTINUOUS"
#	Then user verifies isu "ISU_INACTIVE_BACKLIGHT" with value "5"
#	Then user verifies isu "ISU_NIGHT_TIME_INACTIVE_BACKLIGHT" with value "2"
#	Then user verifies isu "ISU_ACTIVE_BACKLIGHT_START_TIME" with value "28"
#	Then user verifies isu "ISU_NIGHT_TIME_BACKLIGHT_START_TIME" with value "84"
#	Then user verifies isu "ISU_CLOCK_FORMAT" with value "ISU_1410_CLOCK_FORMAT_12HR"
#	Then user verifies isu "ISU_DST_TYPE" with value "ISU_1415_DST_TYPE__ON"
#	Then user verifies isu "ISU_TEMP_OFFSET" with value "ISU_1420_TEMP_OFFSET__0"
#	Then user verifies isu "ISU_HUMID_OFFSET" with value "12"
#	Then user verifies isu "ISU_HOT_WATER_CONTROL_FUNCTION" with value "0"
#	Then user verifies isu "ISU_HOT_WATER_SETPOINT" with value "50"
#	Then user verifies isu "ISU_DISINFECTION_CYCLE" with value "1"
#	Then user verifies isu "ISU_OPENTHERM_MAX_SUPPLY_WATER_TEMPERATURE" with value "60"
#	Then user verifies isu "ISU_OTC_CONTROL" with value "0"
#	Then user verifies isu "ISU_OTC_CURVE" with value "16"
#	Then user verifies isu "ISU_OPENTHERM_ROOM_COMPENSATION" with value "0"
#	Then user verifies isu "ISU_FAIL_SAVE_MODE" with value "0"
#	Then user verifies isu "ISU_DEALER_NAME" with value "0"
#	Then user verifies isu "ISU_DEALER_PHONE" with value "0"
#	Then user verifies isu "ISU_DEALER_EMAIL_ADDRESS" with value "0"
#	Then user verifies isu "ISU_DEALER_WEBSITE" with value "0"
#	Then user verifies isu "ISU_DEALER_MESSAGE" with value "0"